openapi: 3.0.0
servers:
  - url: 'https://api.ringring.be'
    description: prod
info:
  title: RingRing API
  version: 1.8.1
  contact:
    name: API Support
    email: support@ringring.be
    url: 'https://support.ringring.be'
  x-logo:
    url: img/logo_ringring.png
  description: |
    The RingRing API let you send [SMSs](#tag/SMS), [mails](#tag/Mail) and make [voice calls](#tag/Voice).
    In addition to those 3 channels, a contact management system is available under [directory](#tag/Contact).
x-tagGroups:
  - name: Concepts
    tags:
      - concept_auth
      - ratelimit
      - webhook
      - sdk
  - name: General
    tags:
      - Auth
  - name: Channels
    tags:
      - SMS
      - Voice
      - Mail
      - Template
      - OTP
  - name: Directory
    tags:
      - Contact
      - Group
  - name: SMPP
    tags:
      - SMPP_definition
      - SMSC_platform
      - protocol_implementation
tags:
  - name: concept_auth
    x-displayName: Authentication
    x-traitTag: true
    description:
      $ref: auth.md
  - name: ratelimit
    x-displayName: Rate Limit
    x-traitTag: true
    description:
      $ref: ratelimit.md
  - name: webhook
    x-displayName: Webhook
    x-traitTag: true
    description:
      $ref: webhook.md
  - name: sdk
    x-displayName: Libraries & SDK's
    x-traitTag: true
    description: |
      You will find our Message API SDK with examples on GitHub.

      * C# : https://github.com/RingRing-cloud/MessageApiClient-CSharp
      * Java : https://github.com/RingRing-cloud/MessageApiClient-Java
      * PHP : https://github.com/RingRing-cloud/MessageApiClient-PHP

      Think we should add another common language? Feel free to send us an email at coordination@ringring.be !
  - name: Auth
    description: |
      Endpoint for JSON Web Token authentication. Used to retrieve a token for **mail** and **directory**.
  - name: SMS
    x-displayName: SMS (Message API)
    description:
      $ref: sms.md
  - name: Voice
    x-displayName: Voice (Voice API)
    description:
      $ref: voice.md
  - name: Mail
    description:
      $ref: mail.md
  - name: Contact
    description:
      $ref: directory.md
  - name: Group
  - name: SMPP_definition
    x-displayName: SMPP Protocol Definition
    x-traitTag: true
    description:
      $ref: SMPP_definition.md
  - name: SMSC_platform
    x-displayName: RingRing SMSC Platform
    x-traitTag: true
    description:
      $ref: SMSC_platform.md
  - name: protocol_implementation
    x-displayName: SMPP Protocol Implementation
    x-traitTag: true
    description:
      $ref: protocol_implementation.md
paths:
  /portal/auth:
    post:
      summary: Authenticate
      operationId: AuthApiKey_Post
      tags:
        - Auth
      description: |
        This resource is used to authenticate and generate a token to use other APIs from RingRing. The token has a validity duration of 1 hour and will have to be generated again to use the API.

        > You will find your API key on the General settings page of your SMS Mailer application.
  /sms/v1/message:
    post:
      summary: Send SMS
      operationId: MessageApiSmsRequest_Post
      tags:
        - SMS
  /sms/v1/statusmessage:
    get:
      summary: Inspect an SMS
      operationId: MessageApiStatusMessage_Get
      tags:
        - SMS
      description: 'This endpoint allows you to retrieve the status of an individual message. If you need to retrieve the status of all sent messages or of incoming messages, we recommend to use a [webhook](https://developers.ringring.be/#tag/webhook).'
  /sms/v1/cancel:
    post:
      summary: Cancel an SMS
      operationId: MessageApiCancelRequest_Post
      tags:
        - SMS
  /sms/v1/status: {}
  /sms/v1/incoming: {}
  '/sms/v1/Webhooks/{gatewayId}':
    get:
      tags:
        - SMS
      summary: Get webhook(s) configuration(s)
      description: This endpoint allows you to retrieve the webhook configuration for an API key
      operationId: Webhooks_Get
  /sms/v1/Webhooks:
    post:
      tags:
        - SMS
      summary: Update webhook(s) configuration(s)
      description: You can update the webhook(s) onfiguration(s) of your applications (or API keys) using this endpoint
      operationId: Webhooks_PostStatus
  /voice/v1/call:
    post:
      summary: Make call
      operationId: VoiceV1Call_Post
      tags:
        - Voice
      description:
        $ref: voiceapi-call.md
  /voice/v1/voicedeposit:
    post:
      summary: Make voice deposit
      operationId: VoiceV1Deposit
      tags:
        - Voice
      description: |
        ## Leave a Voice message directly on a mobile voicemail box

        > **Limited Availability**
        >
        > The VoiceDeposit API is only available for Belgian mobile phone numbers.
  /voice/v1/voicexml:
    post:
      summary: Make call with VoiceXML
      operationId: VoiceV1CallXml_Post
      description: |
        ## Make an outbound call and route to a VoiceXML application

        ### VoiceXML samples

        Please find below an example of VoiceXML file.
        RingRing provides you some sample available here :

        * [Example in French](https://cdn.ringring.be/public/documentation/VoiceApi/Samples/sample-fr.vxml)
        * [Example in Dutch](https://cdn.ringring.be/public/documentation/VoiceApi/Samples/sample-nl.vxml)
        * [Example in English](https://cdn.ringring.be/public/documentation/VoiceApi/Samples/sample-en.vxml)

        These paths can be used directly in the AnswerUrl field.

        **VoiceXML**

        ```xml
         <vxml version="2.1">
          <catch event="connection.disconnect.hangup">
            <exit/>
          </catch>
          <catch event="connection.disconnect">
            <exit/>
          </catch>
          <form id="myForm">
            <block>
              <prompt xml:lang="en-US">
                Hello and welcome on our automatic call platform.
              </prompt>
              <exit/>
            </block>
          </form>
        </vxml>
        ```
      tags:
        - Voice
  /voice/v1/callstatus:
    post:
      summary: Inspect a call
      operationId: VoiceV1CallStatus
      tags:
        - Voice
      description: |
        > **FeedbackUrl**
        >
        > You will get a similar reponse to the JSON above when using the `FeedbackUrl` parameter in a Call, VoiceDeposit or VoiceXML.
        > Only the `ResultCode` and `ResultDescription` parameters are not sent.
  /voice/v1/cancelcall:
    post:
      summary: Cancel a call
      operationId: VoiceV1CallCancel
      tags:
        - Voice
      description: Cancel a scheduled call
  /voice/v1/prompts:
    post:
      summary: Create a prompt
      operationId: VoiceV1Prompt_Post
      tags:
        - Voice
    get:
      summary: Get all prompts
      operationId: VoiceV1Prompt_Get
      tags:
        - Voice
  '/voice/v1/prompts/{id}':
    get:
      summary: Inspect a prompt
      operationId: VoiceV1Prompt_Get
      tags:
        - Voice
    delete:
      summary: Delete a prompt
      operationId: VoiceV1Prompt_Delete
      tags:
        - Voice
  /mail/mail:
    post:
      tags:
        - Mail
      summary: Send mail
      operationId: Mail_Post
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mail'
          links:
            InspectMailById:
              operationId: MailinspectId_Get
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/UnAuthorized'
        '403':
          $ref: '#/components/responses/InvalidRole'
        '500':
          $ref: '#/components/responses/InternalServerError'
      security:
        - bearerAuth:
            - 'mail:write'
  '/mail/mail/inspect/{id}':
    get:
      tags:
        - Mail
      summary: Inspect a mail
      operationId: MailinspectId_Get
      security:
        - bearerAuth:
            - 'mail:read'
      description: 'Inspect your sent mail. For debugging purposes only [old data are purged], use reporting api or webhook instead'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mail'
          links:
            InspectMailById:
              operationId: MailinspectId_Get
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/UnAuthorized'
        '403':
          $ref: '#/components/responses/InvalidRole'
        '404':
          description: Not Found
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/directory/contact/group/{groupId}':
    get:
      summary: List contacts for a group
      operationId: Contact_Get_groupId_start_limit
      tags:
        - Contact
      security:
        - bearerAuth:
            - contact
  /directory/contact:
    get:
      summary: List contacts
      operationId: Contact_Get_start_limit
      tags:
        - Contact
      security:
        - bearerAuth:
            - contact
    post:
      summary: Create a contact
      operationId: Contact_Post_Contact
      tags:
        - Contact
      security:
        - bearerAuth:
            - contact
  '/directory/contact/{id}':
    get:
      summary: Inspect a contact
      operationId: Contact_Get_id
      tags:
        - Contact
      security:
        - bearerAuth:
            - contact
    put:
      summary: Update a contact
      description: |
        If GroupGuids is null. The groups linked to contact will not change

        If GroupGuids contains value. The groups linked with the contact will be reset and only Groups in the GroupGuids will be linked with the contact.

        If GroupGuids is empty. Contact will be removed from all his current group
      operationId: Contact_Put_id_Contact
      tags:
        - Contact
      security:
        - bearerAuth:
            - contact
    delete:
      summary: Delete a contact
      operationId: Contact_Delete_id
      tags:
        - Contact
      security:
        - bearerAuth:
            - contact
  '/directory/contact/{phoneNumber}':
    get:
      summary: Inspect a contact (by phoneNumber)
      operationId: Contact_Get_phoneNumber
      tags:
        - Contact
      security:
        - bearerAuth:
            - contact
    put:
      summary: Update a contact (by phoneNumber)
      description: "If GroupGuids is null. The groups linked to contact will not change\r\nIf GroupGuids contains value. The groups linked with the contact will be reset and only Groups in the GroupGuids will be linked with the contact.\r\nIf GroupGuids is empty. Contact will be removed from all his current group"
      operationId: Contact_Put_phoneNumber_Contact
      tags:
        - Contact
      security:
        - bearerAuth:
            - contact
    delete:
      summary: Delete a contact (by phoneNumber)
      operationId: Contact_Delete_phoneNumber
      tags:
        - Contact
      security:
        - bearerAuth:
            - contact
  '/directory/contact/{contactId}/group/{groupId}':
    post:
      summary: Add a contact to a group
      operationId: Group_Post_contactId_groupId
      tags:
        - Group
      security:
        - bearerAuth:
            - contact
    delete:
      summary: Remove a contact from a group
      operationId: Group_Delete_contactId_groupId
      tags:
        - Group
      security:
        - bearerAuth:
            - contact
  '/directory/contact/{phoneNumber}/group/{groupId}':
    post:
      summary: Add a contact (by phoneNumber) to a group
      operationId: Group_Post_phoneNumber_groupId
      tags:
        - Group
      security:
        - bearerAuth:
            - contact
    delete:
      summary: Remove a contact (by phoneNumber) from a group
      operationId: Group_Delete_phoneNumber_groupId
      tags:
        - Group
      security:
        - bearerAuth:
            - contact
  /directory/group:
    get:
      summary: List groups
      operationId: Group_Get_start_limit
      tags:
        - Group
      security:
        - bearerAuth:
            - contact
    post:
      summary: Create a group
      operationId: Group_Post_ContactGroup
      tags:
        - Group
      security:
        - bearerAuth:
            - contact
  '/directory/group/{id}':
    get:
      summary: Inspect a group
      operationId: Group_Get_id
      tags:
        - Group
      security:
        - bearerAuth:
            - contact
    put:
      summary: Update a group
      operationId: Group_Put_id_ContactGroup
      tags:
        - Group
      security:
        - bearerAuth:
            - contact
    delete:
      summary: Delete a group
      operationId: Group_Delete_id_deleteAlsoLinkedContact
      tags:
        - Group
      security:
        - bearerAuth:
            - contact
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT