'use strict';

const lib = require('../../lib');

module.exports = {

    receive: async function(context) {

        if (context.properties.generateOutputPortOptions) {
            return this.getOutputPortOptions(context, context.messages.in.content.xConnectorOutputType);
        }

        const limit = context.messages.in.content.xConnectorPaginationLimit;
        const { data } = await this.httpRequest(context);
        const resultsExpression = lib.jsonata('data');
        const result = (await resultsExpression.evaluate(data)).slice(0, limit);

        if (context.messages.in.content.xConnectorOutputType === 'object') {
            return context.sendArray(result, 'out');
        } else {
            // array
            return context.sendJson({ result }, 'out');
        }
    },

    httpRequest: async function(context, override = {}) {

        // eslint-disable-next-line no-unused-vars
        const input = context.messages.in.content;

        let url = lib.getBaseUrl(context) + '/images/generations';

        const headers = {};
        const query = new URLSearchParams;

        const inputMapping = {
            'prompt': input['prompt'],
            'model': input['model'],
            'n': input['n'],
            'quality': input['quality'],
            'response_format': input['response_format'],
            'size': input['size'],
            'style': input['style'],
            'user': input['user']
        };
        let requestBody = {};
        lib.setProperties(requestBody, inputMapping);

        const queryParameters = {  };

        if (override?.query) {
            Object.keys(override.query).forEach(parameter => {
                queryParameters[parameter] = override.query[parameter];
            });
        }

        Object.keys(queryParameters).forEach(parameter => {
            if (queryParameters[parameter]) {
                query.append(parameter, queryParameters[parameter]);
            }
        });

        headers['Authorization'] = 'Bearer {apiKey}'.replace(/{(.*?)}/g, (match, variable) => context.auth[variable]);

        const req = {
            url: url,
            method: 'POST',
            data: requestBody,
            headers: headers
        };

        if (override.url) req.url = override.url;
        if (override.body) req.data = override.body;
        if (override.headers) req.headers = override.headers;
        if (override.method) req.method = override.method;

        const queryString = query.toString();
        if (queryString) {
            req.url += '?' + queryString;
        }

        try {
            const response = await context.httpRequest(req);
            const log = {
                step: 'http-request-success',
                request: {
                    url: req.url,
                    method: req.method,
                    headers: req.headers,
                    data: req.data
                },
                response: {
                    data: response.data,
                    status: response.status,
                    statusText: response.statusText,
                    headers: response.headers
                }
            };
            await context.log(log);
            return response;
        } catch (err) {
            const log = {
                step: 'http-request-error',
                request: {
                    url: req.url,
                    method: req.method,
                    headers: req.headers,
                    data: req.data
                },
                response: err.response ? {
                    data: err.response.data,
                    status: err.response.status,
                    statusText: err.response.statusText,
                    headers: err.response.headers
                } : undefined
            };
            await context.log(log);
            throw err;
        }
    },

    getOutputPortOptions: function(context, xConnectorOutputType) {

        if (xConnectorOutputType === 'object') {
            return context.sendJson(this.objectOutputOptions, 'out');
        } else if (xConnectorOutputType === 'array') {
            return context.sendJson(this.arrayOutputOptions, 'out');
        }
    },

    arrayOutputOptions: [
        {
            'label': 'Result',
            'value': 'result',
            'schema': {
                'type': 'array',
                'items': {
                    'type': 'object',
                    'description': 'Represents the url or the content of an image generated by the OpenAI API.',
                    'x-oaiMeta': {
                        'name': 'The image object',
                        'example': '{\n  "url": "...",\n  "revised_prompt": "..."\n}\n'
                    },
                    'properties': {
                        'b64_json': {
                            'type': 'string',
                            'description': 'The base64-encoded JSON of the generated image, if `response_format` is `b64_json`.'
                        },
                        'url': {
                            'type': 'string',
                            'description': 'The URL of the generated image, if `response_format` is `url` (default).'
                        },
                        'revised_prompt': {
                            'type': 'string',
                            'description': 'The prompt that was used to generate the image, if there was any revision to the prompt.'
                        }
                    }
                }
            }
        }
    ],

    objectOutputOptions: [
        {
            'label': 'B 64 Json',
            'value': 'b64_json'
        },
        {
            'label': 'Url',
            'value': 'url'
        },
        {
            'label': 'Revised Prompt',
            'value': 'revised_prompt'
        }
    ]
};
