{
 "openapi": "3.0.0",
 "info": {
  "contact": {
   "name": "Zoom Developers",
   "url": "https://developer.zoom.us/"
  },
  "description": "The Zoom Meeting API lets developers access information from Zoom. You can use this API to build private services or public applications on the [Zoom App Marketplace](http://marketplace.zoom.us). To learn how to get your credentials and create private/public applications, see our [OAuth](https://marketplace.zoom.us/docs/guides/auth/oauth) documentation. \n\nAll endpoints are available via `https` and are located at `api.zoom.us/v2/`. For example, to list all of an account's use[...]",
  "termsOfService": "https://zoom.us/docs/en-us/zoom_api_license_and_tou.html",
  "title": "Zoom Meeting API",
  "version": "2.0.0"
 },
 "servers": [
  {
   "url": "https://api.zoom.us/v2"
  }
 ],
 "paths": {
  "/accounts/{accountId}/managed_domains": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Accounts"
    ],
    "description": "Use this API to get an account's [managed domains](https://support.zoom.us/hc/en-us/articles/203395207). To get the master account's managed domains, pass the `me` value for the `accountId` path parameter. \n\n **Scopes:** `account:read:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` \n\n **Prerequisites:** \n* A Pro or a higher paid account with the Master account option enabled.",
    "operationId": "accountManagedDomain",
    "summary": "Get account's managed domains"
   }
  },
  "/accounts/{accountId}/settings": {
   "get": {
    "tags": [
     "Accounts"
    ],
    "description": "Use this API to get an account's settings. To get the Master account's settings, use the `me` value for the `accountId` path parameter. \n\n**Scopes:** `account:read:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` \n\n**Prerequisites:** \n* The account must be a paid account.",
    "operationId": "accountSettings",
    "summary": "Get account settings"
   },
   "patch": {
    "tags": [
     "Accounts"
    ],
    "description": "Use this API to update an account's settings. To update the Master account's settings, pass the `me` value for the `accountId` path parameter. \n\n **Scopes:** `account:write:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` \n\n **Prerequisites:** \n* The account must be a paid account.",
    "operationId": "accountSettingsUpdate",
    "summary": "Update account settings"
   }
  },
  "/accounts/{accountId}/lock_settings": {
   "get": {
    "tags": [
     "Accounts"
    ],
    "description": "[Account Locked Settings](https://support.zoom.us/hc/en-us/articles/115005269866) allow you turn settings on or off for all users in your account. No user except the account admin or account owner can change these settings. With lock settings, you force the settings on for all users.\nUse this API to retrieve an account's locked settings. \n\n**Note:** This API can be used by Zoom Accounts that are on a Pro or a higher plan as well accounts that have master and sub accounts o[...]",
    "operationId": "getAccountLockSettings",
    "summary": "Get locked settings"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Accounts"
    ],
    "description": "[Account Locked Settings](https://support.zoom.us/hc/en-us/articles/115005269866) allow you turn settings on or off for all users in your account. No user except the account admin or account owner can change these settings. With lock settings, you force the settings on for all users. Use this API to update an account's locked settings.\n\n**Note:** This API can be used by Zoom Accounts that are on a Pro or a higher plan as well accounts that have master and sub accounts optio[...]",
    "operationId": "updateAccountLockSettings",
    "summary": "Update locked settings"
   }
  },
  "/accounts/{accountId}/settings/registration": {
   "get": {
    "tags": [
     "Accounts"
    ],
    "description": "Use this API to get an account's webinar registration settings. To get the master account's webinar registration settings, use the `me` value for the `accountId` path parameter. \n\n **Scopes:** `account:read:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` \n\n **Prerequisites:** \n* The account must be a paid account.",
    "operationId": "accountSettingsRegistration",
    "summary": "Get an account's webinar registration settings"
   },
   "patch": {
    "tags": [
     "Accounts"
    ],
    "description": "Use this API to update an account's webinar registration settings. To update the master account's webinar registration settings, pass the `me` value for the `accountId` path parameter. \n\n **Scopes:** `account:write:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` \n\n **Prerequisites:** \n* The account must be a paid account.",
    "operationId": "accountSettingsRegistrationUpdate",
    "summary": "Update an account's webinar registration settings"
   }
  },
  "/groups/{groupId}/settings/registration": {
   "get": {
    "tags": [
     "Groups"
    ],
    "description": "Get webinar registration settings for a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-). \n**Prerequisite**: Pro, Business, or Education account<br>\n**Scopes**: `group:read:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "groupSettingsRegistration",
    "summary": "Get a group's webinar registration settings"
   },
   "patch": {
    "tags": [
     "Groups"
    ],
    "description": "Update webinar registration settings for a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-).<p style=\"background-color:#FEEFB3; color:#9F6000\"><br>Note:</b> The `force_pmi_jbh_password` field under meeting settings is planned to be deprecated on September 22, 2019. This field will be replaced by another field that will provide the same functionality.</p>\n**Prerequisite**: Pro, Business, or Education account<br> \n**Scopes**: `group:write:admin[...]",
    "operationId": "groupSettingsRegistrationUpdate",
    "summary": "Update a group's webinar registration settings"
   }
  },
  "/accounts/{accountId}/trusted_domains": {
   "get": {
    "tags": [
     "Accounts"
    ],
    "description": "Use this API to get an account's [trusted domains](https://support.zoom.us/hc/en-us/articles/203395207). To get the Master account's trusted domains, use the `me` value for the `accountId` path parameter. \n\n **Scopes:** `account:read:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` \n\n **Prerequisites:** \n* The account must be a paid account.",
    "operationId": "accountTrustedDomain",
    "summary": "Get account's trusted domains"
   }
  },
  "/archive_files": {
   "get": {
    "tags": [
     "Archiving"
    ],
    "description": "Get an account's archived meeting or webinar files. \n\n Zoom's [archiving solution](https://support.zoom.us/hc/en-us/articles/360050431572-Archiving-indicators) allows account administrators to set up an automated mechanism to record, collect, and archive meeting data to a 3rd-party platform of their choice to satisfy FINRA and/or other compliance requirements. \n\n **Scopes:** `recording:read:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/ra[...]",
    "operationId": "listArchivedFiles",
    "summary": "List archived files"
   }
  },
  "/rooms/calendar/services": {
   "get": {
    "summary": "List calendar services",
    "description": "Use this API to list all the existing [calendar services](https://support.zoom.us/hc/en-us/articles/4409832833037) in a Zoom Room account. \n\n **Scopes:** `room:read:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` \n\n **Prerequisites:** \n* A Pro or a higher plan with a [Zoom Rooms](https://zoom.us/zoomrooms) license.",
    "operationId": "getCalendarServices",
    "tags": [
     "Zoom Rooms Calendar"
    ],
    "security": [
     {
      "OAuth": []
     }
    ]
   }
  },
  "/rooms/calendar/services/{serviceId}": {
   "delete": {
    "summary": "Delete a calendar service",
    "description": "Use this API to delete a Zoom Room account's calendar service. \n\n **Scopes:** `room:write:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` \n\n **Prerequisites:** \n* A Pro or a higher plan with a [Zoom Rooms](https://zoom.us/zoomrooms) license.",
    "operationId": "deleteACalendarService",
    "tags": [
     "Zoom Rooms Calendar"
    ],
    "security": [
     {
      "OAuth": []
     }
    ]
   }
  },
  "/rooms/calendar/services/{serviceId}/sync": {
   "put": {
    "summary": "Start calendar service sync process",
    "description": "Use this API to kick off the sync process for Zoom Room account's calendar service. \n\n **Scopes:** `room:write:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` \n\n **Prerequisites:** \n* A Pro or a higher plan with a [Zoom Rooms](https://zoom.us/zoomrooms) license.",
    "operationId": "syncACalendarService",
    "tags": [
     "Zoom Rooms Calendar"
    ],
    "security": [
     {
      "OAuth": []
     }
    ]
   }
  },
  "/rooms/calendar/services/{serviceId}/resources": {
   "get": {
    "summary": "List calendar resources by calendar service",
    "description": "Use this API to list all of a Zoom Room account's [calendar resources](https://support.zoom.us/hc/en-us/articles/4409832833037). \n\n **Scopes:** `room:read:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` \n\n **Prerequisites:** \n* A Pro or a higher plan with a [Zoom Rooms](https://zoom.us/zoomrooms) license.",
    "operationId": "getCalendarResourcesByServiceId",
    "tags": [
     "Zoom Rooms Calendar"
    ],
    "security": [
     {
      "OAuth": []
     }
    ]
   },
   "post": {
    "summary": "Add a calendar resource to a calendar service",
    "description": "Use this API to add a [calendar resource](https://support.zoom.us/hc/en-us/articles/4409832833037) to a Microsoft Exchange or Office 365 calendar service in a Zoom Room account. \n\n**Note:** This API does not support adding a calendar resource to a Google calendar service. \n\n **Scopes:** `room:write:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` \n\n **Prerequisites:** \n* A Pro or a higher plan with a [[...]",
    "operationId": "addACalendarResourceToCalendarService",
    "tags": [
     "Zoom Rooms Calendar"
    ],
    "security": [
     {
      "OAuth": []
     }
    ]
   }
  },
  "/rooms/calendar/services/{serviceId}/resources/{resourceId}": {
   "get": {
    "summary": "Get a calendar resource by ID",
    "description": "Use this API to get a Zoom Room account's [calendar resource](https://support.zoom.us/hc/en-us/articles/4409832833037). \n\n **Scopes:** `room:read:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` \n\n **Prerequisites:** \n* A Pro or a higher plan with a [Zoom Rooms](https://zoom.us/zoomrooms) license.",
    "operationId": "getCalendarResourceById",
    "tags": [
     "Zoom Rooms Calendar"
    ],
    "security": [
     {
      "OAuth": []
     }
    ]
   },
   "delete": {
    "summary": "Delete a calendar resource",
    "description": "Use this API to delete a Zoom Room account's [calendar resource](https://support.zoom.us/hc/en-us/articles/4409832833037) from a Microsoft Exchange or Office 365 calendar service. \n\n**Note:** This API does not support deleting a calendar resource from a Google calendar service. \n\n **Scopes:** `room:write:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` \n\n **Prerequisites:** \n* A Pro or a higher plan wi[...]",
    "operationId": "deleteACalendarResource",
    "tags": [
     "Zoom Rooms Calendar"
    ],
    "security": [
     {
      "OAuth": []
     }
    ]
   }
  },
  "/groups": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Groups"
    ],
    "description": "List [groups](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) under an account.\n\n**Prerequisite**: Pro or higher account.<br>\n**Scopes**: `group:read:admin`<br>\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "groups",
    "summary": "List groups"
   },
   "post": {
    "summary": "Create a group",
    "description": "Use this API to create a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management). You can add a **maximum** of 100 groups in one account per day, and a maximum of 5000 groups in one account.\n\nIf you enabled a new group via the user interface, you can also choose whether to display the group and set its privacy level.\n\n**Scopes:** `group:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Li[...]",
    "operationId": "groupCreate",
    "tags": [
     "Groups"
    ],
    "security": [
     {
      "OAuth": []
     }
    ]
   }
  },
  "/groups/{groupId}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Groups"
    ],
    "description": "Use this API to delete a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-).\n\n**Scopes:** `group:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* A Pro, Business, or Education account",
    "operationId": "groupDelete",
    "summary": "Delete a group"
   },
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Groups"
    ],
    "description": "Get a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) under an account.\n\n**Prerequisite**: Pro, Business, or Education account<br>\n**Scopes**: `group:read:admin`<br>\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "group",
    "summary": "Get a group"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Groups"
    ],
    "description": "Update a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) under your account.\n\n**Prerequisite**: Pro, Business, or Education account<br>\n**Scopes**: `group:write:admin`<br>\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "groupUpdate",
    "summary": "Update a group"
   }
  },
  "/groups/{groupId}/admins": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Groups"
    ],
    "description": "Use this API to return a list of [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) administrators under your account.\n\n**Scopes:** `group:read:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`\n\n**Prerequisites:** \n* A Pro, Business, or Education account",
    "operationId": "groupAdmins",
    "summary": "List group admins"
   },
   "post": {
    "tags": [
     "Groups"
    ],
    "description": "Use this API to add administrators to a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) under your account.\n\n**Scopes:** `group:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`\n\n**Prerequisites:** \n* A Pro, Business, or Education account",
    "operationId": "groupAdminsCreate",
    "summary": "Add group admins"
   }
  },
  "/groups/{groupId}/admins/{userId}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Groups"
    ],
    "description": "Use this API to remove a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) administrator in a Zoom account.\n\n**Scopes:** `group:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* A Pro, Business, or Education account",
    "operationId": "groupAdminsDelete",
    "summary": "Delete a group admin"
   }
  },
  "/groups/{groupId}/lock_settings": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Groups"
    ],
    "description": "Retrieve a [group's](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) locked settings. If you lock a setting, the group members will not be able to modify it individually. <p style=\"background-color:#FEEFB3; color:#9F6000\"><br>Note:</b> The `force_pmi_jbh_password` field under meeting settings is planned to be deprecated on September 22, 2019. This field will be replaced by another field that will provide the same functionality.</p>\n\n**Prerequisite**[...]",
    "operationId": "getGroupLockSettings",
    "summary": "Get locked settings"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Groups"
    ],
    "description": "Update a [group's](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) locked settings. If you lock a setting, the group members will not be able to modify it individually. <p style=\"background-color:#FEEFB3; color:#9F6000\"><br>Note:</b> The `force_pmi_jbh_password` field under meeting settings is planned to be deprecated on September 22, 2019. This field will be replaced by another field that will provide the same functionality.</p>\n\n**Prerequisite**: [...]",
    "operationId": "groupLockedSettings",
    "summary": "Update locked settings"
   }
  },
  "/groups/{groupId}/members": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Groups"
    ],
    "description": "List the members of a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) under your account.\n\n**Prerequisite**: Pro, Business, or Education account<br>\n**Scopes**: `group:read:admin`<br>\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "groupMembers",
    "summary": "List group members "
   },
   "post": {
    "tags": [
     "Groups"
    ],
    "description": "Use this API to add users to a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) in your account.\n\n**Scopes:** `group:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`\n\n**Prerequisites:** \n* A Pro, Business, or Education account",
    "operationId": "groupMembersCreate",
    "summary": "Add group members"
   }
  },
  "/groups/{groupId}/members/{memberId}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Groups"
    ],
    "description": "Use this API to remove a user from a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) in an account.\n\n**Scopes:** `group:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* A Pro, Business, or Education account",
    "operationId": "groupMembersDelete",
    "summary": "Delete a group member"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Groups"
    ],
    "description": "Use this API to perform either of the following tasks: \n* Remove a group member from one group and move them to a different group. \n* Set a user's primary group. By default, the primary group is the first group that user is added to.\n\nIf a user is a member of multiple groups, you can [assign the user a primary group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-#h_d07c7dcd-4fd8-485a-b5fe-a322e8d21c09). The user will use the primary group's settings[...]",
    "operationId": "updateAGroupMember",
    "summary": "Update a group member"
   }
  },
  "/groups/{groupId}/settings": {
   "get": {
    "summary": "Get a group's settings",
    "description": "Get settings for a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-). \n**Prerequisite**: Pro, Business, or Education account<br>\n**Scopes**: `group:read:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "getGroupSettings",
    "tags": [
     "Groups"
    ],
    "security": [
     {
      "OAuth": []
     }
    ]
   },
   "patch": {
    "tags": [
     "Groups"
    ],
    "description": "Update settings for a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-).<p style=\"background-color:#FEEFB3; color:#9F6000\"><br>Note:</b> The `force_pmi_jbh_password` field under meeting settings is planned to be deprecated on September 22, 2019. This field will be replaced by another field that will provide the same functionality.</p>\n**Prerequisite**: Pro, Business, or Education account<br> \n**Scopes**: `group:write:admin`<br>\n\n **[Rate Lim[...]",
    "operationId": "updateGroupSettings",
    "summary": "Update a group's settings"
   }
  },
  "/groups/{groupId}/settings/virtual_backgrounds": {
   "delete": {
    "tags": [
     "Groups"
    ],
    "description": "Use this API to delete a group's [Virtual Background files](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background#h_01EJF3YFEWGT8YA0ZJ079JEDQE). \n\n **Scope:** `group:write:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` \n\n **Prerequisites:** \n* The [Virtual Background feature](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background#h_2ef28080-fce9-4ac2-b567-dc958afab1b7) m[...]",
    "operationId": "delGroupVB",
    "summary": "Delete Virtual Background files"
   },
   "post": {
    "tags": [
     "Groups"
    ],
    "description": "Use this API to [upload Virtual Background files](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background#h_01EJF3YFEWGT8YA0ZJ079JEDQE) for all users in a group to use. \n\n **Scopes:** `group:write:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` \n\n**Prerequisites:** \n* The [Virtual Background feature](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background#h_2ef28080-fce9-4a[...]",
    "operationId": "uploadGroupVB",
    "summary": "Upload Virtual Background files"
   }
  },
  "/contacts/groups": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Contact Groups"
    ],
    "description": "List [contact groups](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) under an account.\n\n**Prerequisite**: Pro or higher account.<br>\n**Scopes**: `contact_group:read:admin`<br>\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "contactGroups",
    "summary": "List contact groups"
   },
   "post": {
    "summary": "Create a contact group",
    "description": "Use this API to create a [contact group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management).\n\n**Prerequisite**: Pro or higher account.<br>**Scopes:** `contact_group:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "contactGroupCreate",
    "tags": [
     "Contact Groups"
    ],
    "security": [
     {
      "OAuth": []
     }
    ]
   }
  },
  "/contacts/groups/{groupId}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Contact Groups"
    ],
    "description": "Use this API to delete a [contact group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-).\n\n**Prerequisite**: Pro or higher account.<br>**Scopes:** `contact_group:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "contactGroupDelete",
    "summary": "Delete a contact group"
   },
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Contact Groups"
    ],
    "description": "Get a [contact group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) under an account.\n\n**Prerequisite**: Pro or higher account.<br>\n**Scopes**: `contact_group:write:admin`<br>\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "contactGroup",
    "summary": "Get a contact group"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Contact Groups"
    ],
    "description": "Update a [contact group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) under your account.\n\n**Prerequisite**: Pro or higher account.<br>\n**Scopes**: `contact_group:write:admin`<br>\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "contactGroupUpdate",
    "summary": "Update a contact group"
   }
  },
  "/contacts/groups/{groupId}/members": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Contact Groups"
    ],
    "description": "Use this API to remove members in a [contact group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-).\n\n**Prerequisite**: Pro or higher account.<br>**Scopes:** `contact_group:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "contactGroupMemberRemove",
    "summary": "Remove members in a contact group"
   },
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Contact Groups"
    ],
    "description": "List members in [contact groups](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) under an account.\n\n**Prerequisite**: Pro or higher account.<br>\n**Scopes**: `contact_group:read:admin`<br>\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "contactGroupMembers",
    "summary": "List contact group members"
   },
   "post": {
    "summary": "Add contact group members",
    "description": "Use this API to add members to a [contact group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management).\n\n**Prerequisite**: Pro or higher account.<br>**Scopes:** `contact_group:write:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "contactGroupMemberAdd",
    "tags": [
     "Contact Groups"
    ],
    "security": [
     {
      "OAuth": []
     }
    ]
   }
  },
  "/h323/devices": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Devices"
    ],
    "description": "A H.323 or SIP device can make a video call to a [Room Connector](https://support.zoom.us/hc/en-us/articles/201363273-Getting-Started-With-H-323-SIP-Room-Connector) to join a Zoom cloud meeting. A Room Connector can also call out to a H.323 or SIP device to join a Zoom cloud meeting. Use this API to list all H.323/SIP Devices on a Zoom account.<br><br>\n**Scopes:** `h323:read:admin`<br>\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-l[...]",
    "operationId": "deviceList",
    "summary": "List H.323/SIP devices"
   },
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Devices"
    ],
    "description": "A H.323 or SIP device can make a video call to a [Room Connector](https://support.zoom.us/hc/en-us/articles/201363273-Getting-Started-With-H-323-SIP-Room-Connector) to join a Zoom cloud meeting. A Room Connector can also call out to a H.323 or SIP device to join a Zoom cloud meeting. Use this API to add a H.323/SIP device to your Zoom account<br><br>\n**Scopes:** `h323:write:admin`<br>\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-li[...]",
    "operationId": "deviceCreate",
    "summary": "Create a H.323/SIP device"
   }
  },
  "/h323/devices/{deviceId}": {
   "delete": {
    "tags": [
     "Devices"
    ],
    "description": "A H.323 or SIP device can make a video call to a [Room Connector](https://support.zoom.us/hc/en-us/articles/201363273-Getting-Started-With-H-323-SIP-Room-Connector) to join a Zoom cloud meeting. A Room Connector can also call out to a H.323 or SIP device to join a Zoom cloud meeting. Use this API to delete a H.323/SIP device from your Zoom account.<br><br>\n**Scopes:** `h323:write:admin`<br>\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#r[...]",
    "operationId": "deviceDelete",
    "summary": "Delete a H.323/SIP device"
   },
   "patch": {
    "tags": [
     "Devices"
    ],
    "description": "A H.323 or SIP device can make a video call to a [Room Connector](https://support.zoom.us/hc/en-us/articles/201363273-Getting-Started-With-H-323-SIP-Room-Connector) to join a Zoom cloud meeting. A Room Connector can also call out to a H.323 or SIP device to join a Zoom cloud meeting. Use this API to edit information of a H.323/SIP device from your Zoom account.<br><br>\n**Scopes:** `h323:write:admin`<br>\n <br>\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-refer[...]",
    "operationId": "deviceUpdate",
    "summary": "Update a H.323/SIP device"
   }
  },
  "/im/groups": {
   "get": {
    "tags": [
     "IM Groups"
    ],
    "description": "List [IM directory groups](https://support.zoom.us/hc/en-us/articles/203749815-IM-Management).<br><br>\n**Scopes**: `imgroup:read:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "imGroups",
    "summary": "List IM directory groups"
   },
   "post": {
    "tags": [
     "IM Groups"
    ],
    "description": "Create an IM directory group under your account.<br><br>\n**Scopes**: `imgroup:write:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "imGroupCreate",
    "summary": "Create an IM directory group"
   }
  },
  "/im/groups/{groupId}": {
   "delete": {
    "tags": [
     "IM Groups"
    ],
    "description": "Delete an [IM directory group](https://support.zoom.us/hc/en-us/articles/203749815-IM-Management) under your account.<br><br>\nScopes: `imgroup:write:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "imGroupDelete",
    "summary": "Delete an IM directory group"
   },
   "get": {
    "tags": [
     "IM Groups"
    ],
    "description": "Retrieve an [IM directory group](https://support.zoom.us/hc/en-us/articles/203749815-IM-Management) under your account.<br><br>\nScopes: `imgroup:read:admin`<br>\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` ",
    "operationId": "imGroup",
    "summary": "Retrieve an IM directory group"
   },
   "patch": {
    "tags": [
     "IM Groups"
    ],
    "description": "Update an [IM directory group](https://support.zoom.us/hc/en-us/articles/203749815-IM-Management) under your account.<br><br>\n**Scopes**: `imgroup:write:admin`<br>\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "imGroupUpdate",
    "summary": "Update an IM directory group"
   }
  },
  "/im/groups/{groupId}/members": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "IM Groups"
    ],
    "description": "List the members of an [IM directory group](https://support.zoom.us/hc/en-us/articles/203749815-IM-Management).<br><br>\n**Scope:** `imgroup:read:admin`<br>\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "imGroupMembers",
    "summary": "List IM directory group members"
   },
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "IM Groups"
    ],
    "description": "Add members to an [IM directory group](https://support.zoom.us/hc/en-us/articles/203749815-IM-Management) under an account.<br><br>\n**Scope:** `imgroup:write:admin`<br>\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "imGroupMembersCreate",
    "summary": "Add IM directory group members"
   }
  },
  "/im/groups/{groupId}/members/{memberId}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "IM Groups"
    ],
    "description": "Delete a member from an [IM directory group](https://support.zoom.us/hc/en-us/articles/203749815-IM-Management) under an account.<br><br>\nScopes: `imgroup:write:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "imGroupMembersDelete",
    "summary": "Delete IM directory group member"
   }
  },
  "/users/{userId}/meetings": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Meetings"
    ],
    "description": "List a user's (meeting host) scheduled meetings. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter. \n\n**Note:** \n* This API **only** supports scheduled meetings. This API does not return information about instant meetings. \n* This API only returns a user's [unexpired meetings](https://support.zoom.us/hc/en-us/articles/201362373-Meeting-ID#h_c73f9b08-c1c0-4a1a-b538-e01ebb98[...]",
    "operationId": "meetings",
    "summary": "List meetings"
   },
   "post": {
    "tags": [
     "Meetings"
    ],
    "description": "[Create a meeting](https://support.zoom.us/hc/en-us/articles/201362413-Scheduling-meetings) for a user. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\n* A meeting's `start_url` value is the URL a host or an alternative host can use to start a meeting. The expiration time for the `start_url` value is **two hours** for all regular users.\n* For `custCreate` meeting hosts [...]",
    "operationId": "meetingCreate",
    "summary": "Create a meeting"
   }
  },
  "/meetings/{meetingId}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Meetings"
    ],
    "description": "Delete a meeting.<br><br>\n**Scopes:** `meeting:write:admin` `meeting:write`<br>\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` \n\n",
    "operationId": "meetingDelete",
    "summary": "Delete a meeting"
   },
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Meetings"
    ],
    "description": "Retrieve the details of a meeting.<br><br>\n**Scopes:** `meeting:read:admin` `meeting:read`<br>\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` \n\n",
    "operationId": "meeting",
    "summary": "Get a meeting"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Meetings"
    ],
    "description": "Update a meeting's details.\n\n**Note:** \n* This API has a rate limit of **100 requests per day**. Because of this, a meeting can only be updated for a maximum of **100 times within a 24-hour period**. \n* The `start_time` value **must** be a future date. If the value is omitted or a date in the past, the API ignores this value and will **not** update any recurring meetings. \n* If the `start_time` value is a future date, the `recurrence` object is **required**.\n\n**Scopes:[...]",
    "operationId": "meetingUpdate",
    "summary": "Update a meeting"
   }
  },
  "/meetings/{meetingId}/status": {
   "put": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Meetings"
    ],
    "description": "Update the status of a meeting.<br><br>\n**Scopes:** `meeting:write:admin` `meeting:write`\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "meetingStatus",
    "summary": "Update meeting status"
   }
  },
  "/meetings/{meetingId}/invite_links": {
   "post": {
    "summary": "Create meeting's invite links",
    "description": "Create a batch of invitation links for a meeting.\n\n**Scopes**: `meeting:write:admin`, `meeting:write`</br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "tags": [
     "Meetings"
    ],
    "operationId": "meetingInviteLinksCreate",
    "security": [
     {
      "OAuth": []
     }
    ]
   }
  },
  "/information_barriers/policies": {
   "get": {
    "tags": [
     "Information Barriers"
    ],
    "description": "Return a list of all [Information Barriers](https://support.zoom.us/hc/en-us/articles/360040913711-Information-Barriers) policies and their information. \n\n  This API uses [JSON Web Tokens (JWT)](https://marketplace.zoom.us/docs/guides/auth/jwt/) to authenticate account-level access. <br/> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` \n\n**Prerequisites:** \n* [Contact Zoom Support](https://support.zoom.us/hc/en-us/[...]",
    "operationId": "InformationBarriersList",
    "summary": "List information Barrier policies"
   },
   "post": {
    "tags": [
     "Information Barriers"
    ],
    "description": "Create a new Information Barrier policy. [Information Barriers](https://support.zoom.us/hc/en-us/articles/360040913711-Information-Barriers) help customers control communication policies and meet regulatory requirements at scale. Use information barriers to prevent specific groups of users who possess sensitive information from communicating with others who should not know this information. \n\n  This API uses [JSON Web Tokens (JWT)](https://marketplace.zoom.us/docs/guides/au[...]",
    "operationId": "InformationBarriersCreate",
    "summary": "Create an Information Barrier policy"
   }
  },
  "/information_barriers/policies/{policyId}": {
   "delete": {
    "tags": [
     "Information Barriers"
    ],
    "description": "Remove an [Information Barrier](https://support.zoom.us/hc/en-us/articles/360040913711-Information-Barriers) policy.\n\n  This API uses [JSON Web Tokens (JWT)](https://marketplace.zoom.us/docs/guides/auth/jwt/) to authenticate account-level access. <br/> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` \n\n**Prerequisites:** \n* [Contact Zoom Support](https://support.zoom.us/hc/en-us/articles/201362003) to enable Informa[...]",
    "operationId": "InformationBarriersDelete",
    "summary": "Remove an Information Barrier policy"
   },
   "get": {
    "tags": [
     "Information Barriers"
    ],
    "description": "Return an [Information Barriers](https://support.zoom.us/hc/en-us/articles/360040913711-Information-Barriers) policy by its ID. \n\n  This API uses [JSON Web Tokens (JWT)](https://marketplace.zoom.us/docs/guides/auth/jwt/) to authenticate account-level access. <br/> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` \n\n**Prerequisites:** \n* [Contact Zoom Support](https://support.zoom.us/hc/en-us/articles/201362003) to en[...]",
    "operationId": "InformationBarriersGet",
    "summary": "Get an Information Barrier policy by ID"
   },
   "patch": {
    "tags": [
     "Information Barriers"
    ],
    "description": "Update an [Information Barriers](https://support.zoom.us/hc/en-us/articles/360040913711-Information-Barriers) policy.\n\n  This API uses [JSON Web Tokens (JWT)](https://marketplace.zoom.us/docs/guides/auth/jwt/) to authenticate account-level access. <br/> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` \n\n **Prerequisites:** \n* [Contact Zoom Support](https://support.zoom.us/hc/en-us/articles/201362003) to enable Infor[...]",
    "operationId": "InformationBarriersUpdate",
    "summary": "Update an Information Barriers policy"
   }
  },
  "/meetings/{meetingId}/invitation": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Meetings"
    ],
    "description": "Retrieve the meeting invite note that was sent for a specific meeting.<br><br>\n**Scopes:** `meeting:read:admin` `meeting:read`<br>\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n",
    "operationId": "meetingInvitation",
    "summary": "Get meeting invitation"
   }
  },
  "/meetings/{meetingId}/registrants": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Meetings"
    ],
    "description": "A host or a user with admin permission can require [registration for a Zoom meeting](https://support.zoom.us/hc/en-us/articles/211579443-Registration-for-Meetings). List users that have registered for a meeting.<br><br>\n**Scopes**: `meeting:read:admin` `meeting:read`<br>\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "meetingRegistrants",
    "summary": "List meeting registrants"
   },
   "post": {
    "summary": "Add a meeting registrant",
    "description": "Create and submit a user's registration to a meeting. See [Customizing webinar registration](https://support.zoom.us/hc/en-us/articles/202835649-Customizing-webinar-registration) for details on how to set the requirements for these fields. Note that there is a maximum limit of 4,999 registrants per meeting and users will see an error if the meeting's capacity is reached. \n\n **Scopes:** `meeting:write:admin`, `meeting:write` <br> **[Rate Limit Label](https://marketplace.zoom[...]",
    "operationId": "meetingRegistrantCreate",
    "tags": [
     "Meetings"
    ],
    "security": [
     {
      "OAuth": []
     }
    ]
   }
  },
  "/meetings/{meetingId}/batch_registrants": {
   "post": {
    "security": [
     {
      "OAuth": []
     },
     {
      "Bearer": []
     }
    ],
    "tags": [
     "Meetings"
    ],
    "description": "Register up to 30 registrants at once for a meeting that requires [registration](https://support.zoom.us/hc/en-us/articles/211579443-Registration-for-Meetings). <br>\n\n**Prerequisites:**<br>\n* The meeting host must be a Licensed user.\n* The meeting must require registration and should be of type `2`, i.e., they should be scheduled meetings. Instant meetings and Recurring meetings are not supported by this API.<br><br>\n**Scope:** `meeting:write`, `meeting:write:admin`<br>\[...]",
    "operationId": "addBatchRegistrants",
    "summary": "Perform batch registration"
   }
  },
  "/meetings/{meetingId}/registrants/{registrantId}": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Meetings"
    ],
    "description": "Retrieve details on a specific user who has registered for the meeting. A host or a user with administrative permissions can require [registration for Zoom meetings](https://support.zoom.us/hc/en-us/articles/211579443-Registration-for-Meetings).\n\n**Scopes:** `meeting:read:admin`, `meeting:read`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* The account must have a Meeting plan",
    "operationId": "meetingRegistrantGet",
    "summary": "Get a meeting registrant"
   },
   "delete": {
    "tags": [
     "Meetings"
    ],
    "description": "Delete a meeting registrant.<br><br>\n**Scopes**: `meeting:write:admin` `meeting:write`<br>\n <br>\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "meetingregistrantdelete",
    "summary": "Delete a meeting registrant"
   }
  },
  "/meetings/{meetingId}/registrants/status": {
   "put": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Meetings"
    ],
    "description": "Update a meeting registrant's status by either approving, cancelling or denying a registrant from joining the meeting.<br><br>\n**Scopes:** `meeting:write:admin` `meeting:write`\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "meetingRegistrantStatus",
    "summary": "Update registrant's status"
   }
  },
  "/meetings/{meetingId}/registrants/questions": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Meetings"
    ],
    "description": "List registration questions that will be displayed to users while [registering for a meeting](https://support.zoom.us/hc/en-us/articles/211579443-Registration-for-Meetings).<br>\n\n**Scopes:** `meeting:read`, `meeting:read:admin`<br>\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n",
    "operationId": "meetingRegistrantsQuestionsGet",
    "summary": "List registration questions "
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Meetings"
    ],
    "description": "Update registration questions that will be displayed to users while [registering for a meeting](https://support.zoom.us/hc/en-us/articles/211579443-Registration-for-Meetings).<br><br>\n**Scopes:** `meeting:write`, `meeting:write:admin`<br>\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n \n\n",
    "operationId": "meetingRegistrantQuestionUpdate",
    "summary": "Update registration questions"
   }
  },
  "/meetings/{meetingId}/polls": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Meetings"
    ],
    "description": "Polls allow the meeting host to survey attendees. List all [polls](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings) of a meeting.<br><br>\n\n**Scopes**: `meeting:read:admin` `meeting:read`<br>\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n**Prerequisites**:<br>\n* Host user type must be **Pro** or higher plan.\n* Meeting must be a scheduled meeting. Instant meetings do not have polling f[...]",
    "operationId": "meetingPolls",
    "summary": "List meeting polls"
   },
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Meetings"
    ],
    "description": "Polls allow the meeting host to survey attendees. Create a [poll](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings) for a meeting.<br><br>\n\n**Scopes**: `meeting:write:admin` `meeting:write`<br>\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n**Prerequisites**:<br>\n* Host user type must be **Pro** or higher plan.\n* Polling feature must be enabled in the host's account.\n* Meeting must be[...]",
    "operationId": "meetingPollCreate",
    "summary": "Create a meeting poll"
   }
  },
  "/meetings/{meetingId}/batch_polls": {
   "post": {
    "tags": [
     "Meetings"
    ],
    "description": "Polls allow the meeting host to survey attendees. Create batch [polls](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings) for a meeting.<br><br>\n\n**Scopes**: `meeting:write:admin` `meeting:write`<br>\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n**Prerequisites**:<br>\n* Host user type must be **Pro** or higher plan.\n* Polling feature must be enabled in the host's account.\n* Meeting mu[...]",
    "operationId": "createBatchPolls",
    "summary": "Perform batch poll creation"
   }
  },
  "/meetings/{meetingId}/polls/{pollId}": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Meetings"
    ],
    "description": "Polls allow the meeting host to survey attendees. Retrieve information about a specific meeting [poll](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings).<br><br>\n**Scopes**: `meeting:read:admin` `meeting:read`<br>\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n\n",
    "operationId": "meetingPollGet",
    "summary": "Get a meeting poll"
   },
   "put": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Meetings"
    ],
    "description": "Polls allow the meeting host to survey attendees. Update information of a specific meeting [poll](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings)<br><br>\n**Scopes**: `meeting:write:admin` `meeting:write`\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` \n\n",
    "operationId": "meetingPollUpdate",
    "summary": "Update a meeting poll"
   },
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Meetings"
    ],
    "description": "Polls allow the meeting host to survey attendees. Delete a meeting [poll](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings).<br>\n**Scopes**: `meeting:write:admin` `meeting:write`<br>\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` <br>\n**Prerequisites**:<br>\n* Host user type must be **Pro**.\n* Polling feature should be enabled in the host's account.\n* Meeting must be a scheduled meeting. In[...]",
    "operationId": "meetingPollDelete",
    "summary": "Delete a meeting poll"
   }
  },
  "/meetings/{meetingId}/survey": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Meetings"
    ],
    "description": "Return information about a [meeting survey](https://support.zoom.us/hc/en-us/articles/4404969060621-Post-meeting-survey-and-reporting). \n\n **Scopes:** `meeting:read`, `meeting:read:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` \n\n **Prerequisites:** \n* The host must be a **Pro** user type. \n* The [**Meeting Survey**](https://support.zoom.us/hc/en-us/articles/4404939095053-Enabling-meeting-surveys) feat[...]",
    "operationId": "meetingSurveyGet",
    "summary": "Get a meeting survey"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Meetings"
    ],
    "description": "Update a [meeting survey](https://support.zoom.us/hc/en-us/articles/4404969060621-Post-meeting-survey-and-reporting). \n\n **Scopes:** `meeting:write`, `meeting:write:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` \n\n **Prerequisites:** \n* The host must be a **Pro** user type. \n* The [**Meeting Survey**](https://support.zoom.us/hc/en-us/articles/4404939095053-Enabling-meeting-surveys) feature enabled in t[...]",
    "operationId": "meetingSurveyUpdate",
    "summary": "Update a meeting survey"
   },
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Meetings"
    ],
    "description": "Delete a [meeting survey](https://support.zoom.us/hc/en-us/articles/4404969060621-Post-meeting-survey-and-reporting). \n\n **Scopes:** `meeting:write`, `meeting:write:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` \n\n **Prerequisites:** \n* The host must be a **Pro** user type. \n* The [**Meeting Survey**](https://support.zoom.us/hc/en-us/articles/4404939095053-Enabling-meeting-surveys) feature enabled in t[...]",
    "operationId": "meetingSurveyDelete",
    "summary": "Delete a meeting survey"
   }
  },
  "/users/{userId}/meeting_templates": {
   "get": {
    "tags": [
     "Meetings"
    ],
    "description": "List available [meeting templates](https://support.zoom.us/hc/en-us/articles/360036559151-Meeting-templates) for a user. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\n**Scopes:** `meeting:read` or `meeting:read:admin`</br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`\n",
    "operationId": "listMeetingTemplates",
    "summary": "List meeting templates"
   },
   "post": {
    "summary": "Create a meeting template from an existing meeting",
    "description": "Create a meeting template from an existing meeting. \n\n**Scopes**: `meeting:write:admin`, `meeting:write`</br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "meetingTemplateCreate",
    "tags": [
     "Meetings"
    ]
   }
  },
  "/meetings/{meetingId}/livestream": {
   "get": {
    "tags": [
     "Meetings"
    ],
    "description": "Zoom allows users to [livestream a meeting](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service) to a custom platform. Get a meeting's livestream configuration details such as Stream URL, Stream Key and Page URL.<br><br>\n**Prerequisites:**<br>\n* Meeting host must be a licensed user with a Pro or higher plan.<br>\n* Live streaming details must have been [configured](https://support.zoom.us/hc/en-us/articles/115001[...]",
    "operationId": "getMeetingLiveStreamDetails",
    "summary": "Get livestream details"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Meetings"
    ],
    "description": "Update a meeting's livestream information. Zoom allows users to [livestream a meeting](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service) to a custom platform.\n\n**Scopes:** `meeting:write:admin`, `meeting:write`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:** \n* Meeting host must have a Pro license.",
    "operationId": "meetingLiveStreamUpdate",
    "summary": "Update a livestream"
   }
  },
  "/meetings/{meetingId}/livestream/status": {
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Meetings"
    ],
    "description": "Zoom allows users to [livestream a meeting](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service) to a custom platform. Update the status of a meeting's livestream.<br><br>\n**Prerequisites:**<br>\n* Meeting host must have a Pro license.<br>\n**Scopes:** `meeting:write:admin` `meeting:write`<br>\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` \n\n",
    "operationId": "meetingLiveStreamStatusUpdate",
    "summary": "Update Live Stream Status"
   }
  },
  "/past_meetings/{meetingId}/instances": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Meetings"
    ],
    "description": "Return a list of past meeting instances. \n\n **Scopes:** `meeting:read:admin`, `meeting:read` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "pastMeetings",
    "summary": "List past meeting instances"
   }
  },
  "/past_meetings/{meetingId}/polls": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Meetings"
    ],
    "description": "[Polls](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings) allow the meeting host to survey attendees. List poll results of a meeting.<br><br>\n\n**Scopes**: `meeting:read:admin`, `meeting:read`<br>\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` <br>\n**Prerequisites**:<br>\n* Host user type must be **Pro**.\n* Meeting must be a scheduled meeting. Instant meetings do not have polling features e[...]",
    "operationId": "listPastMeetingPolls",
    "summary": "List past meeting's poll results"
   }
  },
  "/past_meetings/{meetingId}": {
   "get": {
    "summary": "Get past meeting details",
    "description": "Get information about a past meeting. \n\n **Scopes:** `meeting:read:admin`, `meeting:read` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "pastMeetingDetails",
    "tags": [
     "Meetings"
    ],
    "security": [
     {
      "OAuth": []
     }
    ]
   }
  },
  "/past_meetings/{meetingId}/participants": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Meetings"
    ],
    "description": "Retrieve information on participants from a past meeting. Note the API doesn't return results if there's only one participant in a meeting.<br><br>\n**Scopes:** `meeting:read:admin` `meeting:read`\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`\n**Prerequisites:**<br>\n* Paid account on a Pro or higher plan.\n\n<br> <br>  **Note**: [Double encode](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis/#meeti[...]",
    "operationId": "pastMeetingParticipants",
    "summary": "Get past meeting participants"
   }
  },
  "/live_meetings/{meetingId}/events": {
   "patch": {
    "tags": [
     "Meetings"
    ],
    "description": "Control [in-meeting](https://support.zoom.us/hc/en-us/articles/360021921032-In-Meeting-Controls) features. In-meeting controls include starting and stopping a recording, pausing and resuming a recording, and inviting participants. \n\n**Note:** This API's recording control only works for cloud recordings. It does **not** work for local recordings. \n\n**Scopes:** `meeting:write`, `meeting:write:admin`, `meeting:master` \n\n**Prerequisites:**\n* The meeting **must** be a live [...]",
    "operationId": "inMeetingControl",
    "summary": "Use in-meeting controls"
   }
  },
  "/live_meetings/{meetingId}/chat/messages/{messageId}": {
   "delete": {
    "summary": "Delete a live meeting message",
    "description": "Deletes a message in a live meeting based on ID. \n\n**Scopes:** `meeting:write` `meeting:write:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "deleteMeetingChatMessageById",
    "tags": [
     "Meetings"
    ],
    "security": [
     {
      "OAuth": []
     }
    ]
   }
  },
  "/meetings/{meetingId}/token": {
   "get": {
    "summary": "Get meeting's token",
    "description": "Get a meeting's [closed caption token (caption URL)](https://support.zoom.us/hc/en-us/articles/115002212983-Using-a-third-party-closed-captioning-service). This token lets you use a third-party service to stream text to their closed captioning software to the Zoom meeting. \n\n**Scopes:** `meeting:read`, `meeting:read:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` \n\n**Prerequisites:** \n* The **Closed capt[...]",
    "tags": [
     "Meetings"
    ],
    "operationId": "meetingToken",
    "security": [
     {
      "OAuth": []
     }
    ]
   }
  },
  "/meetings/{meetingId}/recordings/analytics_summary": {
   "get": {
    "summary": "Get Meeting Recording's Analytics Summary",
    "description": "Use this API to return a meeting recording's [analytics summary](https://support.zoom.us/hc/en-us/articles/205347605-Managing-cloud-recordings#h_0b665029-ce74-4849-9794-d1aa0320d163). **Maximum duration: 1 Month**. To access a password-protected cloud recording, send the user's [OAuth access token](https://marketplace.zoom.us/docs/guides/auth/oauth) as a Bearer token in the Authorization header. For example, \n\n `curl -H \"Authorization: Bearer <ACCESS_TOKEN>\" https://{{bas[...]",
    "operationId": "analytics_summary",
    "tags": [
     "Cloud Recording"
    ]
   }
  },
  "/meetings/{meetingId}/recordings/analytics_details": {
   "get": {
    "summary": "Get Meeting Recording's Analytics Details",
    "description": "Use this API to return a meeting recording's [analytics details](https://support.zoom.us/hc/en-us/articles/205347605-Managing-cloud-recordings#h_0b665029-ce74-4849-9794-d1aa0320d163). **Maximum duration: 1 Month**. To access a password-protected cloud recording, send the user's [OAuth access token](https://marketplace.zoom.us/docs/guides/auth/oauth) as a Bearer token in the Authorization header. For example, \n\n `curl -H \"Authorization: Bearer <ACCESS_TOKEN>\" https://{{bas[...]",
    "operationId": "analytics_details",
    "tags": [
     "Cloud Recording"
    ]
   }
  },
  "/meetings/{meetingId}/recordings": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Cloud Recording"
    ],
    "description": "Delete all recording files of a meeting.<br><br>\n\n**Scopes:** `recording:write:admin` `recording:write`<br> \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n**Prerequisites**:\n* Cloud Recording should be enabled on the user's account.<br>\n",
    "operationId": "recordingDelete",
    "summary": "Delete meeting recordings"
   },
   "get": {
    "summary": "Get meeting recordings",
    "description": "Use this API to return all of a meeting's [recordings](https://support.zoom.us/hc/en-us/articles/203741855-Cloud-Recording#h_7420acb5-1897-4061-87b4-5b76e99c03b4). Use the `download_url` property listed in the response to download the recording files. \n\n To access a password-protected cloud recording, send the user's [OAuth access token](https://marketplace.zoom.us/docs/guides/auth/oauth) as a Bearer token in the Authorization header. For example, \n\n `curl -H \"Authorizat[...]",
    "operationId": "recordingGet",
    "tags": [
     "Cloud Recording"
    ],
    "security": [
     {
      "OAuth": []
     }
    ]
   }
  },
  "/meetings/{meetingId}/recordings/registrants": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Cloud Recording"
    ],
    "description": "Use this API to list registrants of a past meeting's [on-demand cloud recordings](https://support.zoom.us/hc/en-us/articles/360000488283-On-demand-recordings). Users must [register](/docs/api-reference/zoom-api/methods#operation/meetingRecordingRegistrantCreate) to view the recordings. \n\n **Scopes:** `recording:read:admin`, `recording:read` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "meetingRecordingRegistrants",
    "summary": "List recording registrants"
   },
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Cloud Recording"
    ],
    "description": "Cloud Recordings of past Zoom Meetings can be made [on-demand](https://support.zoom.us/hc/en-us/articles/360000488283-On-demand-Recordings). Users should be [registered](/docs/api-reference/zoom-api/methods#operation/meetingRecordingRegistrantCreate) to view these recordings.\n\nUse this API to register a user to gain access to **On-demand Cloud Recordings** of a past meeting.<br>\n**Scopes:** `recording:write:admin`, `recording:write`.<br>\n \n **[Rate Limit Label](https://m[...]",
    "operationId": "meetingRecordingRegistrantCreate",
    "summary": "Create a recording registrant"
   }
  },
  "/meetings/{meetingId}/recordings/registrants/questions": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Cloud Recording"
    ],
    "description": "For [on-demand](https://support.zoom.us/hc/en-us/articles/360000488283-On-demand-Recordings) meeting recordings, you can include fields with questions that will be shown to registrants when they register to view the recording.\n\nUse this API to retrieve a list of questions that are displayed for users to complete when registering to view the recording of a specific meeting.<br>\n**Scopes:** `recording:read:admin`, `recording:read`<br>\n\n **[Rate Limit Label](https://marketp[...]",
    "operationId": "recordingRegistrantsQuestionsGet",
    "summary": "Get registration questions"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Cloud Recording"
    ],
    "description": "For [on-demand](https://support.zoom.us/hc/en-us/articles/360000488283-On-demand-Recordings) meeting recordings, you can include fields with questions that will be shown to registrants when they register to view the recording.\n\nUse this API to update registration questions that are to be answered by users while registering to view a recording.<br>\n**Scopes:** `recording:write:admin`, `recording:write`<br> \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-referen[...]",
    "operationId": "recordingRegistrantQuestionUpdate",
    "summary": "Update registration questions"
   }
  },
  "/meetings/{meetingId}/recordings/registrants/status": {
   "put": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Cloud Recording"
    ],
    "description": "A registrant can either be approved or denied from viewing the [on-demand](https://support.zoom.us/hc/en-us/articles/360000488283-On-demand-Recordings) recording. \nUse this API to update a registrant's status.\n\n**Scopes:** `recording:write:admin`, `recording:write`<br>\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`\n",
    "operationId": "meetingRecordingRegistrantStatus",
    "summary": "Update registrant's status"
   }
  },
  "/meetings/{meetingId}/recordings/settings": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Cloud Recording"
    ],
    "description": "Retrieve settings applied to a meeting's [Cloud Recording](https://support.zoom.us/hc/en-us/articles/203741855-Cloud-Recording).<br><br>\n**Scopes**: `recording:read:admin` `recording:read`<br>\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` <br>",
    "operationId": "recordingSettingUpdate",
    "summary": "Get meeting recording settings"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Cloud Recording"
    ],
    "description": "Update settings applied to a meeting's [Cloud Recording](https://support.zoom.us/hc/en-us/articles/203741855-Cloud-Recording)<br><br>\n**Scopes**: `recording:write:admin` `recording:write`<br>\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` <br>",
    "operationId": "recordingSettingsUpdate",
    "summary": "Update meeting recording settings"
   }
  },
  "/meetings/{meetingUUID}/recordings/status": {
   "put": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Cloud Recording"
    ],
    "description": "Zoom allows users to recover recordings from trash for up to 30 days from the deletion date. Use this API to recover all deleted [Cloud Recordings](https://support.zoom.us/hc/en-us/articles/203741855-Cloud-Recording) of a specific meeting.<br><br>\n**Scopes**: `recording:write:admin` `recording:write`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n**Prerequisites**:<br>\n* A Pro user with Cloud Recording e[...]",
    "operationId": "recordingStatusUpdate",
    "summary": "Recover meeting recordings"
   }
  },
  "/meetings/{meetingId}/recordings/{recordingId}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Cloud Recording"
    ],
    "description": "Delete a specific recording file from a meeting.<p style=\"background-color:#e1f5fe; color:#01579b; padding:8px\"> <b>Note:</b> To use this API, you must enable the <b>The host can delete cloud recordings</b> setting. You can find this setting in the <b>Recording</b> tab of the <b>Settings</b> interface in the [Zoom web portal](https://zoom.us/).</p>\n\n**Scopes**: `recording:write:admin`, `recording:write`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-referenc[...]",
    "operationId": "recordingDeleteOne",
    "summary": "Delete a meeting recording file"
   }
  },
  "/meetings/{meetingId}/recordings/{recordingId}/status": {
   "put": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Cloud Recording"
    ],
    "description": "Zoom allows users to recover recordings from trash for up to 30 days from the deletion date. Use this API to recover a single recording file from the meeting.<br>\n**Scopes:** `recording:write:admin` `recording:write`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n",
    "operationId": "recordingStatusUpdateOne",
    "summary": "Recover a single recording"
   }
  },
  "/meetings/{meetingId}/jointoken/local_recording": {
   "get": {
    "summary": "Get a meeting's join token for local recording",
    "description": "Get a meeting's join token to allow for local recording. The join token lets a recording bot implemented using Zoom Meeting SDK to connect to a Zoom meeting. The recording bot can then automatically start locally recording. This supports both regular and raw local recording types. \n\n**Scopes:** `meeting_token:read:admin:local_recording`, `meeting_token:read:local_recording` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** [...]",
    "tags": [
     "Meetings"
    ],
    "operationId": "meetingLocalRecordingJoinToken",
    "security": [
     {
      "OAuth": []
     }
    ]
   }
  },
  "/meetings/{meetingId}/jointoken/local_archiving": {
   "get": {
    "summary": "Get a meeting's archive token for local archiving",
    "description": "Get a meeting's archive token to allow local archiving. The archive token allows a meeting SDK app or bot to get archive permission to access the meeting's raw audio and video media stream in real-time. \n\n**Scopes:** `meeting_token:read:admin:local_archiving` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` \n\n**Prerequisites:** \n* A Pro or higher plan for the meeting host. \n* The **Archive meetings and webinars[...]",
    "tags": [
     "Meetings"
    ],
    "operationId": "meetingLocalArchivingArchiveToken",
    "security": [
     {
      "OAuth": []
     }
    ]
   }
  },
  "/meetings/{meetingId}/jointoken/live_streaming": {
   "get": {
    "summary": "Get a meeting's join token for live streaming",
    "description": "Get a meeting's join token to allow live streaming. The join token allows a recording bot implemented using Zoom meeting SDK to connect to a Zoom meeting \"hosted by the issuer of the token\", and can call the streaming method automatically. It supports both regular live streaming, and raw streaming. \n\n**Scopes:** `meeting_token:read:admin:live_streaming`, `meeting_token:read:live_streaming` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limit[...]",
    "tags": [
     "Meetings"
    ],
    "operationId": "meetingLiveStreamingJoinToken",
    "security": [
     {
      "OAuth": []
     }
    ]
   }
  },
  "/metrics/chat": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Dashboards"
    ],
    "description": "Get [metrics](https://support.zoom.us/hc/en-us/articles/204654719-Dashboard#h_cc7e9749-1c70-4afb-a9a2-9680654821e4) for how users are utilizing Zoom Chat to send messages.\n\nUse the `from` and `to` query parameters to specify a monthly date range for the dashboard data. The monthly date range must be within the last six months.\n\n> **Note:** To query chat metrics from July 1, 2021 and later, use this endpoint instead of the [**Get IM metrics**](/docs/api-reference/zoom-api/[...]",
    "operationId": "dashboardChat",
    "summary": "Get chat metrics"
   }
  },
  "/metrics/client/feedback": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Dashboards"
    ],
    "description": "Use this API to return [Zoom meetings client feedback](https://support.zoom.us/hc/en-us/articles/115005855266-End-of-Meeting-Feedback-Survey#h_e30d552b-6d8e-4e0a-a588-9ca8180c4dbf) survey results. You can specify a monthly date range for the Dashboard data using the `from` and `to` query parameters. The month should fall within the last six months. \n\n**Scopes:** `dashboard_home:read:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#[...]",
    "operationId": "dashboardClientFeedback",
    "summary": "List Zoom meetings client feedback"
   }
  },
  "/metrics/client/feedback/{feedbackId}": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Dashboards"
    ],
    "description": "Retrieve detailed information on a [Zoom meetings client feedback](https://support.zoom.us/hc/en-us/articles/115005855266-End-of-Meeting-Feedback-Survey#h_e30d552b-6d8e-4e0a-a588-9ca8180c4dbf). <br> You can specify a monthly date range for the dashboard data using the `from` and `to` query parameters. The month should fall within the last six months.\n\n**Prerequisites:**\n* Business or higher account\n* [Feedback to Zoom](https://support.zoom.us/hc/en-us/articles/11500583802[...]",
    "operationId": "dashboardClientFeedbackDetail",
    "summary": "Get zoom meetings client feedback"
   }
  },
  "/metrics/client/satisfaction": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Dashboards"
    ],
    "description": "If the [End of Meeting Feedback Survey](https://support.zoom.us/hc/en-us/articles/115005855266) option is enabled, attendees will be prompted with a survey window where they can tap either the **Thumbs Up** or **Thumbs Down** button that indicates their Zoom meeting experience. With this API, you can get information on the attendees' meeting satisfaction. Specify a monthly date range for the query using the from and to query parameters. The month should fall within the last s[...]",
    "operationId": "listMeetingSatisfaction",
    "summary": "List client meeting satisfaction"
   }
  },
  "/metrics/crc": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Dashboards"
    ],
    "description": "A Cloud Room Connector allows H.323/SIP endpoints to connect to a Zoom meeting. \n\nUse this API to get the hour by hour CRC Port usage for a specified period of time. <aside class='notice'>We will provide the report for a maximum of one month. For example, if \"from\" is set to \"2017-08-05\" and \"to\" is set to \"2017-10-10\", we will adjust \"from\" to \"2017-09-10\".</aside><br><br>\n**Prerequisites:**<br>\n* Business, Education or API Plan.\n* Room Connector must be ena[...]",
    "operationId": "dashboardCRC",
    "summary": "Get CRC port usage"
   }
  },
  "/metrics/im": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Dashboards"
    ],
    "deprecated": true,
    "description": "Get [metrics](https://support.zoom.us/hc/en-us/articles/204654719-Dashboard#h_cc7e9749-1c70-4afb-a9a2-9680654821e4) on how users are utilizing the Zoom Chat client.\n\nYou can specify a monthly date range for the dashboard data using the `from` and `to` query parameters. The month should fall within the last six months.<p style=\"background-color:#e1f5fe; color:#000000; padding:8px\"><b>Deprecated:</b> We will completely deprecate this endpoint in a future release. You can co[...]",
    "operationId": "dashboardIM",
    "summary": "Get IM metrics"
   }
  },
  "/metrics/issues/zoomrooms": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Dashboards"
    ],
    "description": "Get information on top 25 Zoom Rooms with issues in a month. The month specified with the \"from\" and \"to\" range should fall within the last six months.<br>\n**Scope:** `dashboard_home:read:admin`<br>\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>\n**Prerequisites:**<br>\n* Business or a higher plan.\n* Zoom Room must be enabled in the account.",
    "operationId": "dashboardIssueZoomRoom",
    "summary": "Get top 25 Zoom Rooms with issues"
   }
  },
  "/metrics/issues/zoomrooms/{zoomroomId}": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Dashboards"
    ],
    "description": "Use this API to return information about the Zoom Rooms in an account with issues, such as disconnected hardware or bandwidth issues. You can specify a monthly date range for the Dashboard data using the `from` and `to` query parameters. The month should fall within the last six months. \n\n**Scopes:** `dashboard_home:read:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy` \n\n**Prerequisites:** \n* A Business o[...]",
    "operationId": "dashboardIssueDetailZoomRoom",
    "summary": "Get issues of Zoom Rooms"
   }
  },
  "/metrics/meetings": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Dashboards"
    ],
    "description": "List total live or past meetings that occurred during a specified period of time. This overview will show if features such as audio, video, screen sharing, and recording were being used in the meeting. You can also see the license types of each user on your account.<br> You can specify a monthly date range for the dashboard data using the `from` and `to` query parameters. The month should fall within the last six months.<br>\n**Scopes:** `dashboard_meetings:read:admin`<br>\n [...]",
    "operationId": "dashboardMeetings",
    "summary": "List meetings"
   }
  },
  "/metrics/meetings/{meetingId}": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Dashboards"
    ],
    "description": "Get details on live or past meetings. This overview will show if features such as audio, video, screen sharing, and recording were being used in the meeting. You can also see the license types of each user on your account.<br> You can specify a monthly date range for the dashboard data using the `from` and `to` query parameters. The month should fall within the last six months.  <br>\n**Scopes:** `dashboard_meetings:read:admin`<br>\n **[Rate Limit Label](https://marketplace.z[...]",
    "operationId": "dashboardMeetingDetail",
    "summary": "Get meeting details"
   }
  },
  "/metrics/meetings/{meetingId}/participants": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Dashboards"
    ],
    "description": "Use this API to return a list of participants from live or past meetings. \n\n If you do not provide the `type` query parameter, the default value will be set to the `live` value. This API will only return metrics for participants in a live meeting, if any exist. You can specify a monthly date range for the dashboard data using the `from` and `to` query parameters. The month should fall within the last six months. \n\n**Note:** \n\nThis API may return empty values for partici[...]",
    "operationId": "dashboardMeetingParticipants",
    "summary": "List meeting participants"
   }
  },
  "/metrics/meetings/{meetingId}/participants/qos": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Dashboards"
    ],
    "description": "Use this API to return a list of meeting participants from live or past meetings and their quality of service received during the meeting. The data returned indicates the connection quality for sending/receiving video, audio, and shared content. \n\n**Note:** \n\nThis API may return empty values for participants' `user_name`, `ip_address`, `location`, and `email` responses when the account calling this API: \n* Does **not** have a signed HIPAA business associate agreement (BA[...]",
    "operationId": "dashboardMeetingParticipantsQOS",
    "summary": "List meeting participants QoS"
   }
  },
  "/metrics/meetings/{meetingId}/participants/satisfaction": {
   "get": {
    "tags": [
     "Dashboards"
    ],
    "description": "When a meeting ends, each attendee will be prompted to share their meeting experience by clicking either thumbs up or thumbs down. Use this API to retrieve the feedback submitted for a specific meeting. Note that this API only works for meetings scheduled after December 20, 2020.\n\n**Prerequisites:**\n* [Feedback to Zoom](https://support.zoom.us/hc/en-us/articles/115005838023) setting must be enabled by the participant prior to the meeting.\n* The user making the API request[...]",
    "operationId": "participantFeedback",
    "summary": "Get post meeting feedback"
   }
  },
  "/metrics/meetings/{meetingId}/participants/sharing": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Dashboards"
    ],
    "description": "Retrieve the sharing and recording details of participants from live or past meetings.<br>\n**Scopes:** `dashboard_meetings:read:admin`<br>\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>\n**Prerequisites:** <br>\n* Business or a higher plan.",
    "operationId": "dashboardMeetingParticipantShare",
    "summary": "Get meeting sharing/recording details"
   }
  },
  "/metrics/meetings/{meetingId}/participants/{participantId}/qos": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Dashboards"
    ],
    "description": "Use this API to return the quality of service (QoS) report for participants from live or past meetings. The data returned indicates the connection quality for sending/receiving video, audio, and shared content. The API returns this data for either the API request or when the API request was last received. \n\nWhen the sender sends data, a timestamp is attached to the sender's data packet. The receiver then returns this timestamp to the sender. This helps determine the upstrea[...]",
    "operationId": "dashboardMeetingParticipantQOS",
    "summary": "Get meeting participant QoS"
   }
  },
  "/metrics/quality": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Dashboards"
    ],
    "description": "Use this API to return [meeting quality score](https://support.zoom.us/hc/en-us/articles/360061244651-Meeting-quality-scores-and-network-alerts-on-Dashboard) information. Meeting quality scores are based on the mean opinion score (MOS). The MOS measures a meeting's quality on a scale of \"Good\" (5-4), \"Fair\" (4-3), \"Poor\" (3-2), or \"Bad\" (2-1). \n\n**Scopes:** `dashboard_home:read:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limi[...]",
    "operationId": "dashboardQuality",
    "summary": "Get meeting quality scores"
   }
  },
  "/metrics/webinars": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Dashboards"
    ],
    "description": "List all the live or past webinars from a specified period of time. <br><br>\n**Scopes:** `dashboard_webinars:read:admin`<br>\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Resource-intensive`<br>\n**Prerequisites:**<br>\n* Business, Education or API Plan with Webinar add-on.\n\n\n",
    "operationId": "dashboardWebinars",
    "summary": "List webinars"
   }
  },
  "/metrics/webinars/{webinarId}": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Dashboards"
    ],
    "description": "Retrieve details from live or past webinars.<br><br>\n**Scopes:** `dashboard_webinars:read:admin`<br>\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>\n**Prerequisites:**<br>\n* Business, Education or API Plan with Webinar add-on.\n\n",
    "operationId": "dashboardWebinarDetail",
    "summary": "Get webinar details"
   }
  },
  "/metrics/webinars/{webinarId}/participants": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Dashboards"
    ],
    "description": "Use this API to return information about participants from live or past webinars. \n\n**Note:** \n\nThis API may return empty values for participants' `user_name`, `ip_address`, `location`, and `email` responses when the account calling this API: \n* Does **not** have a signed HIPAA business associate agreement (BAA). \n* Is a [**legacy** HIPAA BAA account](https://marketplace.zoom.us/docs/api-reference/other-references/legacy-business-associate-agreements). \n* Displays data[...]",
    "operationId": "dashboardWebinarParticipants",
    "summary": "Get webinar participants"
   }
  },
  "/metrics/webinars/{webinarId}/participants/qos": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Dashboards"
    ],
    "description": "Use this API to return a list of webinar participants from live or past webinars and the quality of service they received during the webinar. The data returned indicates the connection quality for sending/receiving video, audio, and shared content. \n\n**Note:** \n\nThis API may return empty values for participants' `user_name`, `ip_address`, `location`, and `email` responses when the account calling this API: \n* Does **not** have a signed HIPAA business associate agreement [...]",
    "operationId": "dashboardWebinarParticipantsQOS",
    "summary": "List webinar participant QoS"
   }
  },
  "/metrics/webinars/{webinarId}/participants/satisfaction": {
   "get": {
    "tags": [
     "Dashboards"
    ],
    "description": "When a Webinar ends, each attendee will be prompted to share their Webinar experience by clicking either thumbs up or thumbs down. Use this API to retrieve the feedback submitted for a specific webinar. Note that this API only works for meetings scheduled after December 20, 2020.\n\n**Prerequisites:**\n* [Feedback to Zoom](https://support.zoom.us/hc/en-us/articles/115005838023) setting must be enabled by the participant prior to the meeting.\n* The user making the API request[...]",
    "operationId": "participantWebinarFeedback",
    "summary": "Get post webinar feedback"
   }
  },
  "/metrics/webinars/{webinarId}/participants/sharing": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Dashboards"
    ],
    "description": "Retrieve the sharing and recording details of participants from live or past webinars. <br><br>\n**Scopes:** `dashboard_webinars:read:admin`<br>\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy` <br>\n**Prerequisites:**<br>\n* Business, Education or API Plan with Webinar add-on.\n\n",
    "operationId": "dashboardWebinarParticipantShare",
    "summary": "Get webinar sharing/recording details"
   }
  },
  "/metrics/webinars/{webinarId}/participants/{participantId}/qos": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Dashboards"
    ],
    "description": "Use this API to return the quality of service (QoS) for participants during live or past webinars. This data returned indicates the connection quality for sending/receiving video, audio, and shared content. The API returns this data for either the API request or when the API request was last received. \n\nWhen the sender sends its data, a timestamp is attached to the sender's data packet. The receiver then returns this timestamp to the sender. This helps determine the upstrea[...]",
    "operationId": "dashboardWebinarParticipantQOS",
    "summary": "Get webinar participant QoS"
   }
  },
  "/metrics/zoomrooms": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Dashboards"
    ],
    "description": "List information on all Zoom Rooms in an account.<br><br>\n**Scopes:** `dashboard_zr:read:admin`\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Resource-intensive`<br>\n **Prerequisites:**<br>\n* Business, Education or API Plan with Zoom Rooms set up.\n\n\n",
    "operationId": "dashboardZoomRooms",
    "summary": "List Zoom Rooms"
   }
  },
  "/metrics/zoomrooms/issues": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Dashboards"
    ],
    "description": "Get top 25 issues of Zoom Rooms.<br>\n**Scopes:** `dashboard_zr:read:admin`<br>\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>\n **Prerequisites:**<br>\n* Business, Education or API Plan with Zoom Rooms set up.\n\n",
    "operationId": "dashboardZoomRoomIssue",
    "summary": "Get top 25 issues of Zoom Rooms"
   }
  },
  "/metrics/zoomrooms/{zoomroomId}": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Dashboards"
    ],
    "description": "The Zoom Rooms dashboard metrics lets you know the type of configuration a Zoom room has and details on the meetings held in that room. \n\nUse this API to retrieve information on a specific room.<br><br>\n**Scopes:** `dashboard_zr:read:admin`<br> <br>\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`**Prerequisites:**<br>\n* Business, Education or API Plan with Zoom Rooms set up.\n",
    "operationId": "dashboardZoomRoom",
    "summary": "Get Zoom Rooms details"
   }
  },
  "/metrics/client_versions": {
   "get": {
    "summary": "List the client versions",
    "description": "Use this API to list all the client versions and its count. \n\n **Scopes:** `dashboard:read:admin,dashboard_home:read:admin,zms:dashboard:read` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy` \n\n **Prerequisites:** \n* A Business or a higher plan.",
    "operationId": "getClientVersions",
    "tags": [
     "Dashboards"
    ],
    "security": [
     {
      "OAuth": []
     }
    ]
   }
  },
  "/past_meetings/{meetingId}/files": {
   "get": {
    "deprecated": true,
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Deprecated API Endpoints"
    ],
    "description": "**Note: This API has been deprecated and is no longer supported due to GCM encryption updates for security purposes.** To learn about saving the in-meeting chat files via Zoom Client, refer to the [Saving in-meeting chat](https://support.zoom.us/hc/en-us/articles/115004792763-Saving-in-meeting-chat) guide.\n\nList files sent via in-meeting chat during a meeting. The in-meeting files are deleted after 24 hours of the meeting completion time. \n<br><br>\n**Scope:** `meeting:rea[...]",
    "operationId": "listPastMeetingFiles",
    "summary": "List past meeting's files"
   }
  },
  "/past_meetings/{meetingUUID}/archive_files": {
   "delete": {
    "tags": [
     "Archiving"
    ],
    "description": "Use this API to delete all of a meeting's archived files. \n\n **Scopes:** `recording:write:admin`, `recording:write` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` \n\n **Prerequisites:** \n* The [**Meeting and Webinar Archiving** feature](https://support.zoom.us/hc/en-us/articles/4405656451213--Archiving-for-meetings-and-webinars) enabled for your account by [Zoom Support](https://support.zoom.us/hc/en-us/article[...]",
    "operationId": "deleteArchivedFiles",
    "summary": "Delete a meeting's archived files"
   },
   "get": {
    "tags": [
     "Archiving"
    ],
    "description": "Return a specific meeting instance's [archived files](https://support.zoom.us/hc/en-us/articles/360050431572-Archiving-indicators). \n\n **Scopes:** `recording:read` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` \n\n **Prerequisites:** \n* The [**Meeting and Webinar Archiving** feature](https://support.zoom.us/hc/en-us/articles/4405656451213--Archiving-for-meetings-and-webinars) enabled for your account by [Zoom S[...]",
    "operationId": "getArchivedFiles",
    "summary": "Get a meeting's archived files"
   }
  },
  "/archive_files/statistics": {
   "get": {
    "tags": [
     "Archiving"
    ],
    "description": "Get statistics about an account's archived meeting or webinar files. \n\n Zoom's [archiving solution](https://support.zoom.us/hc/en-us/articles/360050431572-Archiving-indicators) lets account administrators set up an automated mechanism to record, collect, and archive meeting data to a third-party platform of their choice to satisfy FINRA and other compliance requirements. \n\n **Scopes:** `recording:read:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-r[...]",
    "operationId": "getArchivedFileStatistics",
    "summary": "Get archived file statistics"
   }
  },
  "/past_webinars/{WebinarUUID}/absentees": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Webinars"
    ],
    "description": "List absentees of a webinar.<br><br>\n**Scopes:** `webinar:read:admin` `webinar:read`<br>\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "webinarAbsentees",
    "summary": "Get webinar absentees"
   }
  },
  "/past_webinars/{webinarId}/files": {
   "get": {
    "deprecated": true,
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Deprecated API Endpoints"
    ],
    "description": "**Note: This API has been deprecated and is no longer supported due to GCM encryption updates for security purposes.**\n\nList files sent via in-meeting chat during a meeting. The in-meeting files are deleted after 24 hours of the meeting completion time. \n<br><br>\n**Scope:** `webinar:read`, `webinar:read:admin`<br>\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br>\n\n",
    "operationId": "listPastWebinarFiles",
    "summary": "List past webinar files"
   }
  },
  "/past_webinars/{webinarId}/instances": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Webinars"
    ],
    "description": "List past webinar instances.<br><br>\n**Scopes:** `webinar:read:admin` `webinar:read`<br>\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n\n",
    "operationId": "pastWebinars",
    "summary": "List past webinar instances"
   }
  },
  "/past_webinars/{webinarId}/participants": {
   "get": {
    "tags": [
     "Webinars"
    ],
    "description": "Use this API to list all the participants who attended a webinar hosted in the past. \n\n**Scopes:** `webinar:read:admin`, `webinar:read` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` \n\n**Prerequisites:** \n* A Pro or higher plan with a Webinar add-on.",
    "operationId": "listWebinarParticipants",
    "summary": "List webinar participants"
   }
  },
  "/past_webinars/{webinarId}/polls": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Webinars"
    ],
    "description": "The polling feature for webinar allows you to create single choice or multiple choice polling questions for your webinars. Use this API to retrieve the results for Webinar Polls of a specific Webinar.\n\n**Prerequisites:**<br>\n* [Webinar license](https://zoom.us/webinar)<br>\n**Scopes**: `webinar:read:admin`, `webinar:read`<br>\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`\n\n",
    "operationId": "listPastWebinarPollResults",
    "summary": "List past webinar poll results"
   }
  },
  "/past_webinars/{webinarId}/qa": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Webinars"
    ],
    "description": "The [Question & Answer (Q&A)](https://support.zoom.us/hc/en-us/articles/203686015-Getting-Started-with-Question-Answer) feature for Webinars allows attendees to ask questions during the Webinar and for the panelists, co-hosts and host to answer their questions.<br>\nUse this API to list Q&A of a specific Webinar.\n\n**Prerequisites:**<br>\n* [Webinar license](https://zoom.us/webinar)<br>\n**Scopes**: `webinar:read:admin`, `webinar:read`<br>\n <br>\n\n\n **[Rate Limit Label](h[...]",
    "operationId": "listPastWebinarQA",
    "summary": "List Q&A of past webinar"
   }
  },
  "/report/activities": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Reports"
    ],
    "description": "Retrieve a list of sign in / sign out activity logs [report](https://support.zoom.us/hc/en-us/articles/201363213-Getting-Started-with-Reports) of users under a Zoom account.<br>\n**Prerequisites**<br>\n* Pro or higher plan.<br>\n**Scopes:** `report:read:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "reportSignInSignOutActivities",
    "summary": "Get sign In / sign out activity report"
   }
  },
  "/report/billing": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Reports"
    ],
    "description": "Get department billing reports of a Zoom account.\n\n**Prerequisites:**<br>\n* Pro or a higher account with Department Billing option enabled. Contact Zoom Support team for details.\n\n**Scopes:** `report:read:admin`, `report:master`\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "getBillingReport",
    "summary": "Get billing reports"
   }
  },
  "/report/billing/invoices": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Reports"
    ],
    "description": "Get department billing invoices reports for a specific billing period. Provide the `billing_id` of the billing period for which you would like to retrieve the invoices for. This ID can be retrieved from **Get Billing Reports** API. \n\n**Prerequisites:**<br>\n* Pro or a higher account with Department Billing option enabled. Contact the Zoom Support team to enable this feature.\n\n**Scopes:** `report:read:admin`, `report:master`\n\n \n **[Rate Limit Label](https://marketplace.[...]",
    "operationId": "getBillingInvoicesReports",
    "summary": "Get billing invoice reports"
   }
  },
  "/report/cloud_recording": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Reports"
    ],
    "description": "Retrieve cloud recording usage report for a specified period. You can only get cloud recording reports that is one day earlier than the current date and for the most recent period of 6 months. The date gap between from and to dates should be smaller or equal to 30 days. <br>\n**Prerequisites**<br>\n* Pro or higher plan.<br>\n**Scopes:** `report:read:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "reportCloudRecording",
    "summary": "Get cloud recording usage report"
   }
  },
  "/report/daily": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Reports"
    ],
    "description": "Retrieve daily report to access the account-wide usage of Zoom services for each day in a given month. It lists the number of new users, meetings, participants, and meeting minutes.<br>\n**Prerequisites**<br>\n* Pro or higher plan.<br>\n**Scopes:** `report:read:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "reportDaily",
    "summary": "Get daily usage report"
   }
  },
  "/report/meetings/{meetingId}": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Reports"
    ],
    "description": "Get a detailed report for a past meeting. <br>\n**Scopes:** `report:read:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>\n**Prerequisites:**<br>\n* Pro or a higher plan.<br>\n ",
    "operationId": "reportMeetingDetails",
    "summary": "Get meeting detail reports"
   }
  },
  "/report/meetings/{meetingId}/participants": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Reports"
    ],
    "description": "Use this API to return a report of a past meeting with two or more participants, including the host. To return a report for past meeting with only **one** participant, use the [**List meeting participants**](/docs/api-reference/zoom-api/ma#operation/dashboardMeetingParticipants) API. \n\n**Note:** \n\nThis API may return empty values for participants' `user_name`, `ip_address`, `location`, and `email` responses when the account calling this API: \n* Does **not** have a signed[...]",
    "operationId": "reportMeetingParticipants",
    "summary": "Get meeting participant reports"
   }
  },
  "/report/meetings/{meetingId}/polls": {
   "get": {
    "summary": "Get meeting poll reports",
    "description": "Use this API to get a report of [poll](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings) results for a past meeting. \n\n **Scopes:** `report:read:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy` \n\n**Prerequisites:** \n* A Pro or a higher plan.",
    "operationId": "reportMeetingPolls",
    "tags": [
     "Reports"
    ],
    "security": [
     {
      "OAuth": []
     }
    ]
   }
  },
  "/report/operationlogs": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Reports"
    ],
    "description": "The [Operations Logs](https://support.zoom.us/hc/en-us/articles/360032748331-Operation-Logs) report allows you to audit admin and user activity, such as adding a new user, changing account settings, and deleting recordings.<br>\nUse this API to retrieve operation logs report for a specified period of time.<br>\n**Scopes:** `report:read:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>\n**Prerequisites:*[...]",
    "operationId": "reportOperationLogs",
    "summary": "Get operation logs report"
   }
  },
  "/report/telephone": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Reports"
    ],
    "description": "The [telephone report](https://support.zoom.us/hc/en-us/articles/206514816-Telephone-reports) allows you to view who dialed into meetings via phone (Audio Conferencing or SIP Connected Audio) and which number they dialed into and other details. Use this API to get telephone report for a specified period of time.\n\n**Scopes:** `report:read:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>**Prerequisites[...]",
    "operationId": "reportTelephone",
    "summary": "Get telephone reports"
   }
  },
  "/report/upcoming_events": {
   "get": {
    "tags": [
     "Reports"
    ],
    "description": "Use this API to list upcoming meeting and/or webinar events within a specified period of time. The report's time range is limited to one month and must also be within the past six months.\n\n**Scopes:** `report:read:admin`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`\n\n**Prerequisites:** \n* A Pro or higher plan",
    "operationId": "reportUpcomingEvents",
    "summary": "Get upcoming events report"
   }
  },
  "/report/users": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Reports"
    ],
    "description": "A user is considered to be an active host during the month specified in the \"from\" and \"to\" range, if the user has hosted at least one meeting during this period. If the user didn't host any meetings during this period, the user is considered to be inactive.<br>The Active Hosts report displays a list of meetings, participants, and meeting minutes for a specific time range, up to one month. The month should fall within the last six months.<br>The Inactive Hosts report pull[...]",
    "operationId": "reportUsers",
    "summary": "Get active/inactive host reports"
   }
  },
  "/report/users/{userId}/meetings": {
   "get": {
    "tags": [
     "Reports"
    ],
    "description": "Retrieve [report](https://support.zoom.us/hc/en-us/articles/216378603-Meeting-Reporting) on past meetings and webinars for a specified time period. The time range for the report is limited to a month and the month must fall within the past six months.\n\nMeetings and webinars are returned only if they have two or more unique participants.  <br><br>\n**Scopes:** `report:read:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-li[...]",
    "operationId": "reportMeetings",
    "summary": "Get meeting reports"
   }
  },
  "/report/webinars/{webinarId}": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Reports"
    ],
    "description": "Retrieve a [report](https://support.zoom.us/hc/en-us/articles/201393719-Webinar-Reporting) containing past webinar details.  <br><br>\n**Scopes:** `report:read:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>\n**Prerequisites:**<br>\n* Pro or higher plan with Webinar add-on.",
    "operationId": "reportWebinarDetails",
    "summary": "Get webinar detail reports"
   }
  },
  "/report/webinars/{webinarId}/participants": {
   "get": {
    "summary": "Get webinar participant reports",
    "description": "Use this API to get a detailed report on each webinar attendee. You can get webinar participant reports for the last 6 months. \n\n **Scopes:** `report:read:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy` \n\n**Prerequisites:** \n* A Pro or a higher plan with Webinar add-on enabled.",
    "operationId": "reportWebinarParticipants",
    "tags": [
     "Reports"
    ],
    "security": [
     {
      "OAuth": []
     }
    ]
   }
  },
  "/report/webinars/{webinarId}/polls": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Reports"
    ],
    "description": "Retrieve a report on past [webinar polls](https://support.zoom.us/hc/en-us/articles/203749865-Polling-for-Webinars).<br><br>\n**Scopes:** `report:read:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>\n**Prerequisites:**<br>\n* Pro or a higher plan with Webinar add-on enabled.",
    "operationId": "reportWebinarPolls",
    "summary": "Get webinar poll reports"
   }
  },
  "/report/webinars/{webinarId}/qa": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Reports"
    ],
    "description": "The Question & Answer (Q&A) feature for webinars allows attendees to ask questions during the webinar and for the panelists, co-hosts and host to answer their questions.\n\nUse this API to retrieve a report on question and answers from past webinars. <br><br>\n**Scopes:** `report:read:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>\n**Prerequisites:**<br>\n* Pro or a higher plan with Webinar add-on en[...]",
    "operationId": "reportWebinarQA",
    "summary": "Get webinar Q&A report"
   }
  },
  "/roles": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Roles"
    ],
    "description": "List [roles](https://support.zoom.us/hc/en-us/articles/115001078646-Role-Based-Access-Control) on your account\n\n**Scopes:** `role:read:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br>\n**Prerequisites** :\n*  Pro or higher plan. \n*  For setting the initial role, you must be the Account Owner. \n*  For subsequent role management, you must be the Account Owner or user with role management permissions[...]",
    "operationId": "roles",
    "summary": "List roles"
   },
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Roles"
    ],
    "description": "Each Zoom user automatically has a role which can either be owner, administrator, or a member. \n\n**Pre-requisite:**<br>\n* Pro or higher plan.\n* For setting the initial role, you must be the Account Owner.<br>\n* For subsequent role management, you must be the Account Owner or user with role management permissions.<br>\n**Scopes:** `role:write:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "createRole",
    "summary": "Create a role"
   }
  },
  "/roles/{roleId}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Roles"
    ],
    "description": "Each Zoom user automatically has a role which can either be owner, administrator, or a member. Account Owners and users with edit privileges for Role management can add customized roles with a list.\n\nUse this API to delete a role.<br>\n**Pre-requisite:**<br>\n* A Pro or higher plan.<br>\n* For role management and updates, you must be the Account Owner or user with role management permissions.\n\n**Scopes:** `role:write:admin`<br>\n \n **[Rate Limit Label](https://marketplac[...]",
    "operationId": "deleteRole",
    "summary": "Delete a role"
   },
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Roles"
    ],
    "description": "Each Zoom user automatically has a role which can either be owner, administrator, or a member. Account Owners and users with edit privileges for Role management can add customized roles with a list of privileges.\n\nUse this API to get information including specific privileges assigned to a [role](https://support.zoom.us/hc/en-us/articles/115001078646-Role-Based-Access-Control).<br>\n**Pre-requisite:**<br>\n* A Pro or higher plan.<br>\n* For role management and updates, you m[...]",
    "operationId": "getRoleInformation",
    "summary": "Get role information"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Roles"
    ],
    "description": "Each Zoom user automatically has a [role](https://support.zoom.us/hc/en-us/articles/115001078646-Role-Based-Access-Control) which can either be owner, administrator, or a member. Account Owners and users with edit privileges for Role management can add customized roles with a list.\n\nUse this API to change the privileges, name and description of a specific role.<br>\n**Pre-requisite:**<br>\n* A Pro or higher plan.<br>\n* For role management and updates, you must be the Accou[...]",
    "operationId": "updateRole",
    "summary": "Update role information"
   }
  },
  "/roles/{roleId}/members": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Roles"
    ],
    "description": "User [roles](https://support.zoom.us/hc/en-us/articles/115001078646-Role-Based-Access-Control) can have a set of permissions that allows access only to the pages a user needs to view or edit. Use this API to list all the members that are assigned a specific role.\n\n**Scope:** `role:read:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br>**Prerequisites:**<br>\n* A Pro or a higher plan.",
    "operationId": "roleMembers",
    "summary": "List members in a role"
   },
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Roles"
    ],
    "description": "User [roles](https://support.zoom.us/hc/en-us/articles/115001078646-Role-Based-Access-Control) can have a set of permissions that allows access only to the pages a user needs to view or edit. Use this API to [assign a role](https://support.zoom.us/hc/en-us/articles/115001078646-Role-Based-Access-Control#h_748b6fd8-5057-4cf4-bbfd-787909c09db0) to members.\n\n**Scopes:** `role:write:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#[...]",
    "operationId": "AddRoleMembers",
    "summary": "Assign a role"
   }
  },
  "/roles/{roleId}/members/{memberId}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Roles"
    ],
    "description": "User [roles](https://support.zoom.us/hc/en-us/articles/115001078646-Role-Based-Access-Control) can have a set of permissions that allows access only to the pages a user needs to view or edit. Use this API to unassign a user's role.\n\n**Scope:** `role:write:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n**Prerequisites:**<br>\n* A Pro or a higher plan.",
    "operationId": "roleMemberDelete",
    "summary": "Unassign a role"
   }
  },
  "/rooms": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Zoom Rooms"
    ],
    "description": "Zoom Rooms is a software-based room system that provides an integrated experience for audio conferencing, wireless screen sharing and video conferencing. Use this API to list all the existing [Zoom Rooms](https://support.zoom.us/hc/en-us/articles/207483343-Getting-Started-with-Zoom-Rooms) in a Zoom account.<br><br>\n**Prerequisites:**<br>\n* Pro or a higher plan with [Zoom Room](https://zoom.us/zoomrooms) license.<br>\n**Scopes**: `room:read:admin`<br> \n **[Rate Limit Label][...]",
    "operationId": "listZoomRooms",
    "summary": "List Zoom Rooms"
   },
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Zoom Rooms"
    ],
    "description": "Use this API to [add a Zoom Room](https://support.zoom.us/hc/en-us/articles/202822279-Add-Zoom-Rooms-on-Web-Portal) to a Zoom account.<br><br>\n**Prerequisites:**<br>\n* Pro or a higher plan with [Zoom Room](https://zoom.us/zoomrooms) license.<br>\n**Scopes**: `room:write:admin`<br> \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "addARoom",
    "summary": "Add a Zoom Room"
   }
  },
  "/rooms/account_profile": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Zoom Rooms Account"
    ],
    "description": "Get details on the account profile of a Zoom Room. This information can only by accessed either by the Zoom Room Account Owner or a user with Zoom Rooms admin permission. To get information on an individual Room Profile, use the [**Get Zoom Room profile**](/docs/api-reference/zoom-api/methods#operation/getZRProfile) API. \n\n**Prerequisites:**<br>\n* Zoom account owner or Zoom Rooms admin permissions<br>\n\n**Scopes:** `room:read:admin`<br> \n **[Rate Limit Label](https://mar[...]",
    "operationId": "getZRAccountProfile",
    "summary": "Get Zoom Room account profile"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Zoom Rooms Account"
    ],
    "description": "Update information on the account profile of a Zoom Room. This information can only by accessed either by the Zoom Room Account Owner or a user with Zoom Rooms admin permission. To update information on an individual Room Profile, use the [**Update a Zoom Room profile**](/docs/api-reference/zoom-api/methods#operation/updateRoomProfile) API. \n\n**Prerequisites:**<br>\n* Zoom account owner or Zoom Rooms admin permissions<br>\n\n**Scopes:** `room:write:admin`<br> \n **[Rate Lim[...]",
    "operationId": "updateZRAccProfile",
    "summary": "Update Zoom Room account profile"
   }
  },
  "/rooms/account_settings": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Zoom Rooms Account"
    ],
    "description": "Get details on Account Settings of a Zoom Room. With this API, you can view either the **Account Meeting Settings** or the **Alert Settings** (Client Alert Settings and Notification Settings) of the Zoom Rooms account. By default, only **Account Meeting Settings** are returned. To view only **Alert Settings**, specify `alert` as the value of the `setting_type` query parameter.<br><br>\n**Prerequisites:**<br>\n* Zoom Room licenses\n* Owner or Admin privileges on the Zoom Accou[...]",
    "operationId": "getZRAccountSettings",
    "summary": "Get Zoom Room account settings"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Zoom Rooms Account"
    ],
    "description": "Update account settings applied for Zoom Rooms in a Zoom account. With this API, you can update either the **Account Meeting Settings** or the **Alert Settings** (Client Alert Settings and Notification Settings) of the Zoom Rooms account by specifying the required setting type in the `setting_type` parameter. To update only **Alert Settings**, specify `alert` as the value of the `setting_type` query parameter and to update only **Account Meeting Settings**, specify `meeting` [...]",
    "operationId": "updateZoomRoomAccSettings",
    "summary": "Update Zoom Room account settings"
   }
  },
  "/rooms/digital_signage": {
   "get": {
    "tags": [
     "Zoom Rooms"
    ],
    "description": "Use this API to return information about a Zoom account's [Zoom Rooms digital signage content](https://support.zoom.us/hc/en-us/articles/360000030683-Zoom-Rooms-digital-signage). You can also view this content in the **Room Management** section's [**Digital Signage Content**](https://zoom.us/digitalsignage#/) tab in the Zoom web portal. \n\n**Scopes:** `room:read:admin` \n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium[...]",
    "operationId": "listDigitalSignageContent",
    "summary": "List digital signage contents"
   }
  },
  "/rooms/events": {
   "patch": {
    "tags": [
     "Zoom Rooms"
    ],
    "description": "Display or hide E911 emergency alert text content from [Zoom Rooms digital signage](https://support.zoom.us/hc/en-us/articles/360000030683-Zoom-Rooms-digital-signage).\n\n**Scope:** `room:write:admin` \n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` \n\n**Prerequisites:**<br>\n* [Zoom Rooms](https://zoom.us/zoomrooms/software) 5.3.0 or higher\n* Zoom Rooms digital signage must be [enabled](https://support.zoom.us/hc/[...]",
    "operationId": "manageE911signage",
    "summary": "Update E911 digital signage"
   }
  },
  "/rooms/locations": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Zoom Rooms Location"
    ],
    "description": "A Zoom account owner or a Zoom Room administrator can establish a [location hierarchy](https://support.zoom.us/hc/en-us/articles/115000342983-Zoom-Rooms-Location-Hierarchy) to help manage Zoom Rooms that are spread among a variety of locations. Use this API to list the different location types used for Zoom Rooms in an account.<br><br>\n**Prerequisites:**\n* Account owner or admin permissions.\n* Zoom Rooms Version 4.0 or higher<br><br>\n**Scopes:** `room:read:admin`<br> \n \[...]",
    "operationId": "listZRLocations",
    "summary": "List Zoom Room locations"
   },
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Zoom Rooms Location"
    ],
    "description": "Add a location to the [location hierarchial structure(s)](https://support.zoom.us/hc/en-us/articles/115000342983-Zoom-Rooms-Location-Hierarchy) of Zoom Rooms in an account.\n\n**Prerequisites:**\n* Account owner or admin permissions.\n* Zoom Rooms Version 4.0 or higher<br><br>\n**Scopes:** `room:write:admin`<br> \n\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "addAZRLocation",
    "summary": "Add a location"
   }
  },
  "/rooms/locations/structure": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Zoom Rooms Location"
    ],
    "description": "Get the [location hierarchial structure(s)](https://support.zoom.us/hc/en-us/articles/115000342983-Zoom-Rooms-Location-Hierarchy) applied on the Zoom Rooms in an account.<br><br>\n**Prerequisites:**<br>\n* Zoom Rooms version 4.0 or higher\n* Account owner or admin permissions<br>\n**Scopes:** `room:read:admin`<br> \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "getZRLocationStructure",
    "summary": "Get Zoom Room location structure"
   },
   "put": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Zoom Rooms Location"
    ],
    "description": "Update the [location hierarchial structure(s)](https://support.zoom.us/hc/en-us/articles/115000342983-Zoom-Rooms-Location-Hierarchy) applied on the Zoom Rooms in an account.<br><br>\n**Prerequisites:**<br>\n* Zoom Rooms version 4.0 or higher\n* Account owner or admin permissions<br>\n**Scopes:** `room:write:admin`<br> \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "updateZoomRoomsLocationStructure",
    "summary": "Update Zoom Rooms location structure"
   }
  },
  "/rooms/locations/{locationId}": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Zoom Rooms Location"
    ],
    "description": "Each location type of the [Zoom Rooms location hierarchy](https://support.zoom.us/hc/en-us/articles/115000342983-Zoom-Rooms-Location-Hierarchy) has a profile page that includes information such as name of the location, address, support email, etc. Use this API to retrieve information about a specific Zoom Rooms location type such as information about the city where the Zoom Rooms is located.\n\n**Prerequisite:**<br>\n* Account owner or admin permission\n* Zoom Rooms version 4[...]",
    "operationId": "getZRLocationProfile",
    "summary": "Get Zoom Room location profile"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Zoom Rooms Location"
    ],
    "description": "Each location type of the [Zoom Rooms location hierarchy](https://support.zoom.us/hc/en-us/articles/115000342983-Zoom-Rooms-Location-Hierarchy) has a profile page that includes information such as name of the location, address, support email, etc. Use this API to update information about a specific Zoom Rooms location type such as information about the city where the Zoom Rooms is located.\n\n**Prerequisite:**<br>\n* Account owner or admin permission\n* Zoom Rooms version 4.0[...]",
    "operationId": "updateZRLocationProfile",
    "summary": "Update Zoom Room location profile"
   }
  },
  "/rooms/locations/{locationId}/location": {
   "put": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Zoom Rooms Location"
    ],
    "description": "An account owner of a Zoom account can establish a [Zoom Rooms Location Hierarchy](https://support.zoom.us/hc/en-us/articles/115000342983-Zoom-Rooms-Location-Hierarchy) to better organize Zoom Rooms spread across various locations. The location can be structured in a hierarchy with Country being the top-level location, followed by city, campus, building, and floor. The location in the lower level in the hierarchy is considered as a child of the location that is a level above [...]",
    "operationId": "changeParentLocation",
    "summary": "Change the assigned parent location"
   }
  },
  "/rooms/locations/{locationId}/settings": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Zoom Rooms Location"
    ],
    "description": "Get information on meeting or alert settings applied to Zoom Rooms located in a specific location. By default, only **Meeting Settings** are returned. To view only **Alert Settings**, specify `alert` as the value of the `setting_type` query parameter.<br><br>\n**Prerequisites:**<br>\n* Zoom Room licenses\n* Owner or Admin privileges on the Zoom Account.<br>\n**Scopes:** `room:read:admin`<br> \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#ra[...]",
    "operationId": "getZRLocationSettings",
    "summary": "Get location settings"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Zoom Rooms Location"
    ],
    "description": "Update information on either meeting or alert settings applied to Zoom Rooms located in a specific location. To update **Alert Settings**, specify `alert` as the value of the `setting_type` query parameter. Similarly, to update **Meeting Settings**, specify `meeting` as the value of the `setting_type` query parameter.<br><br>\n**Prerequisites:**<br>\n* Zoom Room licenses\n* Owner or Admin privileges on the Zoom Account.<br>\n**Scopes:** `room:write:admin`<br> \n **[Rate Limit[...]",
    "operationId": "updateZRLocationSettings",
    "summary": "Update location settings"
   }
  },
  "/rooms/{id}/events": {
   "patch": {
    "tags": [
     "Zoom Rooms"
    ],
    "description": "Use this API to control [Zoom Rooms](https://support.zoom.us/hc/en-us/articles/207483343), including room check-in and check-out, mute on and off, incoming meeting request accept or decline, meeting join, leave, or end, room restart, and cancellation. \n\n**Prerequisites:**\n* [Zoom Rooms](https://support.zoom.us/hc/en-us/articles/207483343-Getting-started-with-Zoom-Rooms#:~:text=Zoom%20Rooms%20is%20a%20software,or%20from%20their%20mobile%20device) must have been set up for u[...]",
    "operationId": "ZoomRoomsControls",
    "summary": "Use Zoom Room controls"
   }
  },
  "/rooms/{roomId}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Zoom Rooms"
    ],
    "description": "[Remove](https://support.zoom.us/hc/en-us/articles/360033432032-Zoom-Room-Device-Profiles#h_e55b2092-c418-4b02-819f-44de51448900) a specific Zoom Room profile from a Zoom account.<br><br>\n**Prerequisites:**<br>\n* Pro or a higher plan with [Zoom Room](https://zoom.us/zoomrooms) license.<br>\n**Scopes**: `room:write:admin`<br> \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "deleteAZoomRoom",
    "summary": "Delete a Zoom Room"
   },
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Zoom Rooms"
    ],
    "description": "\nZoom Rooms is a software-based room system that provides an integrated experience for audio conferencing, wireless screen sharing and video conferencing. Use this API to get detailed information on a specific Zoom Room in a Zoom account.\n\n**Prerequisites:**<br>\n* Pro or a higher plan with [Zoom Room](https://zoom.us/zoomrooms) license.<br>\n**Scopes**: `room:read:admin`<br> \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**[...]",
    "operationId": "getZRProfile",
    "summary": "Get Zoom Room profile"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Zoom Rooms"
    ],
    "description": "Update basic information on a specific Zoom Room in a Zoom account.<br>\n\n**Prerequisites:**<br>\n* Pro or a higher plan with [Zoom Room](https://zoom.us/zoomrooms) license.<br>\n**Scopes**: `room:write:admin`<br> \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "updateRoomProfile",
    "summary": "Update a Zoom Room profile"
   }
  },
  "/rooms/{roomId}/device_profiles": {
   "get": {
    "tags": [
     "Zoom Rooms"
    ],
    "description": "Use this API to return a list of Zoom Room device profiles. \n\n **Scopes:** `room:read:admin` \n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` \n\n **Prerequisites:** \n* A Pro or a higher account with Zoom Rooms.",
    "operationId": "getRoomProfiles",
    "summary": "List device profiles"
   },
   "post": {
    "tags": [
     "Zoom Rooms"
    ],
    "description": "Use this API to create a Zoom Room device profile. \n\n **Scopes:** `room:write:admin` \n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` \n\n **Prerequisites:** \n* A Pro or a higher account with Zoom Rooms.",
    "operationId": "createRoomDeviceProfile",
    "summary": "Create a device profile"
   }
  },
  "/rooms/{roomId}/device_profiles/devices": {
   "get": {
    "tags": [
     "Zoom Rooms"
    ],
    "description": "Use this API to return information about a Zoom Room device. \n\n **Scopes:** `room:read:admin` \n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` \n\n **Prerequisites:** \n* A Pro or a higher account with Zoom Rooms.",
    "operationId": "getRoomDevices",
    "summary": "Get device information"
   }
  },
  "/rooms/{roomId}/device_profiles/{deviceProfileId}": {
   "delete": {
    "tags": [
     "Zoom Rooms"
    ],
    "description": "Use this API to delete a Zoom Room device profile. \n\n **Scopes:** `room:write:admin` \n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` \n\n **Prerequisites:** \n* A Pro or a higher account with Zoom Rooms.",
    "operationId": "deleteRoomProfile",
    "summary": "Delete a device profile"
   },
   "get": {
    "tags": [
     "Zoom Rooms"
    ],
    "description": "Use this API to return a Zoom Room device profile. \n\n **Scopes:** `room:read:admin` \n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` \n\n **Prerequisites:** \n* A Pro or a higher account with Zoom Rooms.",
    "operationId": "getRoomProfile",
    "summary": "Get a device profile"
   },
   "patch": {
    "summary": "Update a device profile",
    "description": "Use this API to update a Zoom Room device profile. \n\n **Scopes:** `room:write:admin` \n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` \n\n **Prerequisites:** \n* A Pro or a higher account with Zoom Rooms.",
    "operationId": "updateDeviceProfile",
    "tags": [
     "Zoom Rooms"
    ]
   }
  },
  "/rooms/{roomId}/devices": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Zoom Rooms"
    ],
    "description": "List information about the devices that are being used for a specific [Zoom Room](https://support.zoom.us/hc/en-us/articles/207483343-Getting-Started-with-Zoom-Rooms) in an account.\n\n**Prerequisites:**<br>\n* Pro or a higher plan with [Zoom Room](https://zoom.us/zoomrooms) license.<br>\n* Account owner or admin permissions.\n**Scopes**: `room:read:admin`<br> \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "listZRDevices",
    "summary": "List Zoom Room devices"
   }
  },
  "/rooms/{roomId}/devices/{deviceId}": {
   "delete": {
    "description": "Use this API to delete a Zoom Room device. \n\n **Prerequisites:** <br> \n* Pro or a higher plan with [Zoom Room](https://zoom.us/zoomrooms) license.<br>\n* Account owner or admin permissions.\n**Scopes**: `room:write:admin`<br> \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "deleteDevice",
    "summary": "Delete a Zoom Room user device",
    "tags": [
     "Zoom Rooms Devices"
    ],
    "security": [
     {
      "OAuth": []
     }
    ]
   }
  },
  "/rooms/{roomId}/devices/{deviceId}/app_version": {
   "put": {
    "tags": [
     "Zoom Rooms Devices"
    ],
    "description": "Use this API to [upgrade or downgrade](https://support.zoom.us/hc/en-us/articles/204675449-Upgrade-or-Downgrade-Zoom-Rooms-Software) the version of your installed Zoom Rooms app on your Mac or Windows device. \n\n**Scopes:** `room:write:admin` \n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` \n\n**Prerequisites:** \n* A Pro or a higher account with Zoom Rooms. \n* The Zoom Rooms software must be installed on a Mac or[...]",
    "operationId": "changeZoomRoomsAppVersion",
    "summary": "Change Zoom Rooms app version"
   }
  },
  "/rooms/{roomId}/location": {
   "put": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Zoom Rooms"
    ],
    "description": "An account owner of a Zoom account can establish a [Zoom Rooms Location Hierarchy](https://support.zoom.us/hc/en-us/articles/115000342983-Zoom-Rooms-Location-Hierarchy) to better organize Zoom Rooms spread across various locations. The location can be structured in a hierarchy with Country being the top-level location, followed by city, campus, building, and floor. Use this API to assign a new location for a Zoom Room. Note that the Zoom Room can be assigned only to the lowes[...]",
    "operationId": "changeZRLocation",
    "summary": "Change a Zoom Room's location"
   }
  },
  "/rooms/{roomId}/settings": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Zoom Rooms"
    ],
    "description": "Get information on meeting or alert settings applied to a specific Zoom Room. By default, only **Meeting Settings** are returned. To view only **Alert Settings**, specify `alert` as the value of the `setting_type` query parameter.<br>\n**Prerequisites:**<br>\n* Zoom Room licenses\n* Owner or Admin privileges on the Zoom Account.<br>\n**Scopes:** `room:read:admin`\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br> [...]",
    "operationId": "getZRSettings",
    "summary": "Get Zoom Room settings"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Zoom Rooms"
    ],
    "description": "Update either meeting or alert settings applied to a specific Zoom Room. To update **Alert Settings**, specify `alert` as the value of the `setting_type` query parameter. To update **Meeting Settings**, specify `meeting` as the value of the `setting_type` query parameter.<br>\n**Prerequisites:**<br>\n* Zoom Room licenses\n* Owner or Admin privileges on the Zoom Account.<br>\n**Scopes:** `room:write:admin`<br> \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-refere[...]",
    "operationId": "updateZRSettings",
    "summary": "Update Zoom Room settings"
   }
  },
  "/rooms/{roomId}/sensor_data": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Zoom Rooms"
    ],
    "description": "Use this API to get the sensor data from the specified Zoom Room. <br>\n**Prerequisites:**<br>\n* Zoom Room licenses\n* Owner or Admin privileges on the Zoom Account.<br>\n**Scopes:** `room:read:admin`\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br> ",
    "operationId": "getZRSensorData",
    "summary": "Get Zoom Room sensor data"
   }
  },
  "/sip_phones": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "SIP Phone"
    ],
    "description": "Zoom's Phone System Integration (PSI), also referred as SIP phones, enables an organization to leverage the Zoom client to complete a softphone registration to supported premise based PBX system. End users will have the ability to have softphone functionality within a single client while maintaining a comparable interface to Zoom Phone. Use this API to list SIP phones on an account.<br><br>\n**Prerequisites**:\n* Currently only supported on Cisco and Avaya PBX systems. \n* Us[...]",
    "operationId": "listSipPhones",
    "summary": "List SIP phones"
   },
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "SIP Phone"
    ],
    "description": "Zoom's Phone System Integration (PSI), also referred as SIP phones, enables an organization to leverage the Zoom client to complete a softphone registration to supported premise based PBX system. End users will have the ability to have softphone functionality within a single client while maintaining a comparable interface to Zoom Phone. Use this API to enable a user to use SIP phone.<br><br>\n**Prerequisites**:\n* Currently only supported on Cisco and Avaya PBX systems. \n* T[...]",
    "operationId": "createSIPPhone",
    "summary": "Enable SIP phone"
   }
  },
  "/sip_phones/{phoneId}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "SIP Phone"
    ],
    "description": "Use this API to delete a Zoom account's SIP phone. \n\n **Scopes:** `sip_phone:write:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` \n\n**Prerequisites**: \n* Currently only supported on Cisco and Avaya PBX systems. \n* The user must enable **SIP Phone Integration** by contacting the [Zoom Sales](https://zoom.us/contactsales) team.",
    "operationId": "deleteSIPPhone",
    "summary": "Delete SIP phone"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "SIP Phone"
    ],
    "description": "Zoom's Phone System Integration (PSI), also referred as SIP phones, enables an organization to leverage the Zoom client to complete a softphone registration to supported premise based PBX system. End users will have the ability to have softphone functionality within a single client while maintaining a comparable interface to Zoom Phone. Use this API to update information of a specific SIP Phone on a Zoom account.<br><br>\n**Prerequisites**:\n* Currently only supported on Cisc[...]",
    "operationId": "updateSIPPhone",
    "summary": "Update SIP phone"
   }
  },
  "/tracking_fields": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Tracking Field"
    ],
    "description": "Use this API to list all the [tracking fields](https://support.zoom.us/hc/en-us/articles/115000293426-Scheduling-Tracking-Fields) on your Zoom account. Tracking fields let you analyze usage by various fields within an organization. \n\n**Scopes:** `tracking_fields:read:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` \n\n**Prerequisites:** \n* A Business, Education, API or higher plan.",
    "operationId": "trackingfieldList",
    "summary": "List tracking fields"
   },
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Tracking Field"
    ],
    "description": "Use this API to create a new [tracking field](https://support.zoom.us/hc/en-us/articles/115000293426-Scheduling-Tracking-Fields). Tracking fields let you analyze usage by various fields within an organization. When scheduling a meeting, tracking fields will be included in the meeting options. \n\n**Scope:** `tracking_fields:write:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` \n\n**Prerequisites:** \n* A Bus[...]",
    "operationId": "trackingfieldCreate",
    "summary": "Create a tracking field"
   }
  },
  "/tracking_fields/{fieldId}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Tracking Field"
    ],
    "description": "Use this API to delete a [tracking field](https://support.zoom.us/hc/en-us/articles/115000293426-Scheduling-Tracking-Fields). \n\n**Scope:** `tracking_fields:write:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` \n\n**Prerequisites:** \n* A Business, Education, API or higher plan.",
    "operationId": "trackingfieldDelete",
    "summary": "Delete a tracking field"
   },
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Tracking Field"
    ],
    "description": "Use this API to return information about a [tracking field](https://support.zoom.us/hc/en-us/articles/115000293426-Scheduling-Tracking-Fields). \n\n**Scopes:** `tracking_fields:read:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` \n\n**Prerequisites:** \n* A Business, Education, API or higher plan.",
    "operationId": "trackingfieldGet",
    "summary": "Get a tracking field"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Tracking Field"
    ],
    "description": "Use this API to update a [tracking field](https://support.zoom.us/hc/en-us/articles/115000293426-Scheduling-Tracking-Fields). \n\n**Scope:** `tracking_fields:write:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` \n\n**Prerequisites:** \n* A Business, Education, API or higher plan.",
    "operationId": "trackingfieldUpdate",
    "summary": "Update a tracking field"
   }
  },
  "/tsp": {
   "get": {
    "tags": [
     "TSP"
    ],
    "description": "Get information on Telephony Service Provider on an account level.<br><br>\n**Scopes:** `tsp:read:admin` <br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:**<br>\n* A Pro or a higher plan.",
    "operationId": "tsp",
    "summary": "Get account's TSP information"
   },
   "patch": {
    "tags": [
     "TSP"
    ],
    "description": "Update information of the Telephony Service Provider set up on an account.<br>\n**Prerequisites**:<br>\nTSP account option should be enabled.<br>\n**Scopes:** `tsp:write:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n",
    "operationId": "tspUpdate",
    "summary": "Update account's TSP information"
   }
  },
  "/users": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Users"
    ],
    "description": "Use this API to list your account's users. \n\n**Scopes:** `user:read:admin` \n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "users",
    "summary": "List users"
   },
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Users"
    ],
    "description": "Add a new user to your Zoom account. \n\n**Scopes:** `user:write:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` \n\n **Note:** The following rate limits apply when you use the `create` value for the `action` field: \n* 50 requests per day for **Free** accounts. \n* 1,500 requests per day for **Pro** accounts. \n* 10,000 requests per day for **Business+** accounts. \n\n**Prerequisites:** \n* A Pro or higher p[...]",
    "operationId": "userCreate",
    "summary": "Create users"
   }
  },
  "/users/email": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Users"
    ],
    "description": "Verify if a user's email is registered with Zoom.<br><br>\n\n<b>Note: </b>You can successfully check if a user is a registered Zoom user only if the user **signed up for Zoom via email and is within your account.** If you provide an email address of a user who is not in your account, the value of \"existed_email\" parameter will be \"false\" irrespective of whether or not the user is registered with Zoom. The response of this API call will not include users who joined Zoom us[...]",
    "operationId": "userEmail",
    "summary": "Check a user email"
   }
  },
  "/users/me/zak": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Users"
    ],
    "description": "Get the Zoom Access Key (ZAK) for the authenticated user associated with the access token in the API request. You can use a ZAK to start or join a meeting on behalf of this user.\n\nZAKs obtained with this endpoint expire five minutes after receipt.\n\nTo get a ZAK for a different user or with a different expiration, use the [Get a user token](https://marketplace.zoom.us/docs/api-reference/zoom-api/methods#operation/userToken) API with the `zak` `type` query parameter.\n\nSee[...]",
    "operationId": "userZak",
    "summary": "Get the user's ZAK"
   }
  },
  "/users/vanity_name": {
   "get": {
    "tags": [
     "Users"
    ],
    "description": "A personal meeting room is a virtual meeting room that can be permanently assigned to a user.\nUse this API to check if a personal meeting room with the given name exists or not.<br><br>\n**Scopes:** `user:read:admin` `user:read`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` ",
    "operationId": "userVanityName",
    "summary": "Check a user's PM room"
   }
  },
  "/users/{userId}": {
   "delete": {
    "tags": [
     "Users"
    ],
    "description": "Use this API to disassociate (unlink) a user or permanently delete a user. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\nThis does not satisfy the deletion requirements of a [Data Subject Access Request (DSAR)](https://dataprivacymanager.net/what-is-data-subject-access-request-dsar/). For a DSAR request, contact Zoom Support. Zoom does not perform DSAR requests through[...]",
    "operationId": "userDelete",
    "summary": "Delete a user"
   },
   "get": {
    "tags": [
     "Users"
    ],
    "description": "Use this API to view a user's information on a Zoom account. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter. \n\n**Note:** Users who have not activated their account will have a `pending` status. These users' `created_at` timestamp will also display the time at which the API call was made, **not** the account's creation date. \n\n**Scopes:** `user:read:admin`, `user:read`, [...]",
    "operationId": "user",
    "summary": "Get a user"
   },
   "patch": {
    "summary": "Update a user",
    "description": "Use this API to update a user's [Zoom profile](https://support.zoom.us/hc/en-us/articles/201363203-My-Profile) information. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\n**Scopes:** `user:write:admin` `user:write`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "userUpdate",
    "tags": [
     "Users"
    ]
   }
  },
  "/users/{userId}/assistants": {
   "delete": {
    "tags": [
     "Users"
    ],
    "description": "Delete all assistants of the current user. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\nAssistants are the users to whom the current user has assigned [scheduling privilege](https://support.zoom.us/hc/en-us/articles/201362803-Scheduling-Privilege). These assistants can schedule meeting on behalf of the current user as well as manage and act as an alternative host for [...]",
    "operationId": "userAssistantsDelete",
    "summary": "Delete user assistants"
   },
   "get": {
    "tags": [
     "Users"
    ],
    "description": "List a user's assistants. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\nAssistants are the users to whom the current user has assigned [scheduling privilege](https://support.zoom.us/hc/en-us/articles/201362803-Scheduling-Privilege). These assistants can schedule meeting on behalf of the current user as well as manage and act as an alternative host for all meetings if t[...]",
    "operationId": "userAssistants",
    "summary": "List user assistants"
   },
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Users"
    ],
    "description": "Use this API to assign assistants to a user. In the request body, provide either the user's ID or the user's email address. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter. \n\n Assistants are users to whom the current user has assigned the [scheduling privilege](https://support.zoom.us/hc/en-us/articles/201362803-Scheduling-Privilege). These assistants can schedule meetings[...]",
    "operationId": "userAssistantCreate",
    "summary": "Add assistants"
   }
  },
  "/users/{userId}/assistants/{assistantId}": {
   "delete": {
    "tags": [
     "Users"
    ],
    "description": "Delete a specific assistant of a user. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\nAssistants are the users to whom the current user has assigned [scheduling privilege](https://support.zoom.us/hc/en-us/articles/201362803-Scheduling-Privilege). These assistants can schedule meeting on behalf of the current user as well as manage and act as an alternative host for all [...]",
    "operationId": "userAssistantDelete",
    "summary": "Delete a user assistant"
   }
  },
  "/users/{userId}/collaboration_devices": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Users"
    ],
    "description": "List a user's collaboration devices. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\n**Scopes:** `user:read:admin`, `user:read`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "listCollaborationDevices",
    "summary": "List a user's collaboration devices"
   }
  },
  "/users/{userId}/collaboration_devices/{collaborationDeviceId}": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Users"
    ],
    "description": "Get collaboration device detail. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\n**Scopes:** `user:read:admin`, `user:read`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "getCollaborationDevice",
    "summary": "Get collaboration device detail"
   }
  },
  "/users/{userId}/email": {
   "put": {
    "tags": [
     "Users"
    ],
    "description": "Change a user's [email address](https://support.zoom.us/hc/en-us/articles/201362563-How-Do-I-Change-the-Email-on-My-Account-) on a Zoom account that has managed domain set up. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\n* If the Zoom account in which the user belongs has multiple [managed domains](https://support.zoom.us/hc/en-us/articles/203395207-What-is-Managed-Do[...]",
    "operationId": "userEmailUpdate",
    "summary": "Update a user's email"
   }
  },
  "/users/{userId}/pac": {
   "get": {
    "tags": [
     "PAC"
    ],
    "description": "Use this API to list a user's [Personal Audio Conference (PAC)](https://support.zoom.us/hc/en-us/articles/204517069-Getting-Started-with-Personal-Audio-Conference) accounts. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter. \n\n PAC allows Pro or higher account holders to host meetings through PSTN (phone dial-in) only. \n\n **Scopes:** `pac:read:admin`, `pac:read` <br> **[Ra[...]",
    "operationId": "userPACs",
    "summary": "List a user's PAC accounts"
   }
  },
  "/users/{userId}/password": {
   "put": {
    "tags": [
     "Users"
    ],
    "description": "Update the [password](https://support.zoom.us/hc/en-us/articles/206344385-Change-a-User-s-Password) of a user using which the user can login to Zoom. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\nAfter this request is processed successfully, an email notification will be sent to the user stating that the password was changed.<br>\n**Scopes:** `user:write:admin` `user:w[...]",
    "operationId": "userPassword",
    "summary": "Update a user's password"
   }
  },
  "/users/{userId}/permissions": {
   "get": {
    "tags": [
     "Users"
    ],
    "description": "Use this API to get permissions that have been granted to the user. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\nUsers can be assigned a set of permissions that allows them to access only the pages/information that a user needs to view or edit.\n\n**Scopes:** `user:read:admin`, `user:read`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-lim[...]",
    "operationId": "userPermission",
    "summary": "Get user permissions"
   }
  },
  "/users/{userId}/picture": {
   "delete": {
    "tags": [
     "Users"
    ],
    "description": "Use this API to delete a user's profile picture. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter. \n\n**Scopes:** `user:write:admin`, `user:write` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "userPictureDelete",
    "summary": "Delete a user's profile picture"
   },
   "post": {
    "tags": [
     "Users"
    ],
    "description": "Upload a user's profile picture. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\nProvide `multipart/form-data` as the value of the `content-type` header for this request. This API supports `.jpeg` and `.png` file formats.\n\n**Scopes:** `user:write:admin`, `user:write`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Med[...]",
    "operationId": "userPicture",
    "summary": "Upload a user's profile picture"
   }
  },
  "/users/{userId}/presence_status": {
   "put": {
    "summary": "Update a user's presence status",
    "description": "Use this API to update a user's presence status. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\nA user's status **cannot** be updated more than once per minute. For example, you can only submit a maximum of one update request per minute for a single user.\n\nUsers in the Zoom desktop client and mobile apps are assigned with a [presence status](https://support.zoom.us/hc[...]",
    "operationId": "updatePresenceStatus",
    "tags": [
     "Users"
    ]
   }
  },
  "/users/{userId}/recordings": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Cloud Recording"
    ],
    "description": "Use this API to list all [cloud recordings](https://support.zoom.us/hc/en-us/articles/203741855-Cloud-Recording) of a user. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\nTo access a user's password protected cloud recording, send the user's [OAuth access token](https://marketplace.zoom.us/docs/guides/auth/oauth) as a Bearer token in the Authorization header. For exampl[...]",
    "operationId": "recordingsList",
    "summary": "List all recordings"
   }
  },
  "/users/{userId}/schedulers": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Users"
    ],
    "description": "Delete all of a user's schedulers. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\nSchedulers are users on whose behalf the current user (assistant) can schedule meetings for. By calling this API, the current user will no longer be a scheduling assistant of any user. \n\n**Scopes:** `user:write:admin`, `user:write`</br>**[Rate Limit Label](https://marketplace.zoom.us/doc[...]",
    "operationId": "userSchedulersDelete",
    "summary": "Delete user schedulers"
   },
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Users"
    ],
    "description": "List all the schedulers of a user. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\nSchedulers in this context are the users for whom the current user can schedule meetings for. For example, if the current user (the user whose `userId` was passed in the `path` parameter) is \"user A\", the response of this API will contain a list of user(s), for whom user A can schedule a[...]",
    "operationId": "userSchedulers",
    "summary": "List user schedulers"
   }
  },
  "/users/{userId}/schedulers/{schedulerId}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Users"
    ],
    "description": "Delete a scheduler. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\nSchedulers are users on whose behalf the current user (assistant) can schedule meetings for. By calling this API, the current user will no longer be a scheduling assistant of this scheduler.\n\n**Scopes:** `user:write:admin`, `user:write`</br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-refe[...]",
    "operationId": "userSchedulerDelete",
    "summary": "Delete a scheduler"
   }
  },
  "/users/{userId}/settings": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Users"
    ],
    "description": "Retrieve a user's settings. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\n**Scopes:** `user:read:admin`, `user:read`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "userSettings",
    "summary": "Get user settings"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Users"
    ],
    "description": "Update a user's settings. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\n**Scopes:** `user:write:admin`, `user:write`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "userSettingsUpdate",
    "summary": "Update user settings"
   }
  },
  "/users/{userId}/settings/virtual_backgrounds": {
   "delete": {
    "tags": [
     "Users"
    ],
    "description": "Use this API to delete a user's Virtual Background files. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter. \n\n **Scopes:** `user:write`, `user:write:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` \n\n **Prerequisites:** \n* The [Virtual Background feature](https://support.zoom.us/hc/en-us/articles/21070750[...]",
    "operationId": "delUserVB",
    "summary": "Delete Virtual Background files"
   },
   "post": {
    "tags": [
     "Users"
    ],
    "description": "Use this API to [upload a Virtual Background files](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background) to a user's profile. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter. \n\n **Note:** \n* A user profile cannot exceed more than 10 Virtual Background files. \n* You can only upload image files that are in JPG/JPEG, GIF or PNG format. \n* Video files mus[...]",
    "operationId": "uploadVBuser",
    "summary": "Upload Virtual Background files"
   }
  },
  "/users/{userId}/status": {
   "put": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Users"
    ],
    "description": "Use this API to [deactivate](https://support.zoom.us/hc/en-us/articles/115005269946-Remove-User-from-your-Account#h_6a9bc1c3-d739-4945-b1f2-00b3b88fb5cc) an active user or to [reactivate](https://support.zoom.us/hc/en-us/articles/115005269946-Remove-User-from-your-Account#h_16319724-d120-4be6-af5d-31582d134ea0) a deactivated user. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parame[...]",
    "operationId": "userStatus",
    "summary": "Update user status"
   }
  },
  "/users/{userId}/token": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Users"
    ],
    "description": "Revoke a user's SSO token. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\nAfter calling this API, the SSO user will be logged out of their current Zoom session.\n\n**Scopes:** `user:write:admin`, `user:write`<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "userSSOTokenDelete",
    "summary": "Revoke a user's SSO token"
   },
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Users"
    ],
    "description": "Use this API to get a user's Zoom token or Zoom Access Key (ZAK). For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter. \n\n **Scopes:** `user:read:admin`, `user:read` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "userToken",
    "summary": "Get a user's token"
   }
  },
  "/users/features": {
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Users"
    ],
    "description": "Use this API to bulk update features. \n\n**Scopes:** `user:write:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`.",
    "operationId": "bulkUpdateFeature",
    "summary": "Bulk update feature"
   }
  },
  "/users/{userId}/tsp": {
   "get": {
    "tags": [
     "TSP"
    ],
    "description": "A user can have a maximum of two TSP accounts. Use this API to list all TSP accounts of a user.<br><br>\n**Scopes:** `tsp:read:admin` `tsp:read`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "userTSPs",
    "summary": "List user's TSP accounts"
   },
   "post": {
    "tags": [
     "TSP"
    ],
    "description": "Add a user's TSP account.<br><br>\n**Scopes:** `tsp:write:admin` `tsp:write`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n",
    "operationId": "userTSPCreate",
    "summary": "Add a user's TSP account"
   }
  },
  "/users/{userId}/tsp/settings": {
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "TSP"
    ],
    "description": "A global dial-in page can provide a list of global access numbers using which audio conferencing can be conducted. By calling this API, you can set the url for the global dial-in page of a user whose Zoom account has TSP and special TSP with third-party audio conferencing options enabled. <p></p>\n**Scopes:**`tsp:write:admin` `tsp:write`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n",
    "operationId": "tspUrlUpdate",
    "summary": "Set global dial-in URL for a TSP user"
   }
  },
  "/users/{userId}/tsp/{tspId}": {
   "delete": {
    "tags": [
     "TSP"
    ],
    "description": "Delete a user's TSP account.<br><br>\n**Scopes:** `tsp:write:admin` `tsp:write`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n",
    "operationId": "userTSPDelete",
    "summary": "Delete a user's TSP account"
   },
   "get": {
    "tags": [
     "TSP"
    ],
    "description": "Each user can have a maximum of two TSP accounts. Use this API to retrieve details of a specific TSP account enabled for a specific user.<br><br>\n**Scopes:** `tsp:read:admin` `tsp:read`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n",
    "operationId": "userTSP",
    "summary": "Get a user's TSP account"
   },
   "patch": {
    "tags": [
     "TSP"
    ],
    "description": "Update a user's TSP account.<br><br>\n**Scopes:** `tsp:write:admin` `tsp:write`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n",
    "operationId": "userTSPUpdate",
    "summary": "Update a TSP account"
   }
  },
  "/users/{userId}/webinar_templates": {
   "get": {
    "summary": "List webinar templates",
    "description": "Use this API to list a user's [webinar templates](https://support.zoom.us/hc/en-us/articles/115001079746-Webinar-Templates). For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter. \n\nWhen you schedule a webinar, you can save the settings for that webinar as a template for scheduling future webinars.  To use a template when scheduling a webinar, use the `id` value in this API resp[...]",
    "operationId": "listWebinarTemplates",
    "tags": [
     "Webinars"
    ]
   },
   "post": {
    "summary": "Create a webinar template",
    "description": "Use this API to create a webinar template from an existing webinar. \n\n**Scopes**: `webinar:write:admin`, `webinar:write`</br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "webinarTemplateCreate",
    "tags": [
     "Webinars"
    ]
   }
  },
  "/users/{userId}/webinars": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Webinars"
    ],
    "description": "Use this API to list all the webinars scheduled by or on-behalf a user (webinar host). For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter. \n\n Zoom users with a [Webinar Plan](https://zoom.us/webinar) have access to creating and managing webinars. Webinars allow a host to broadcast a Zoom meeting to up to 10,000 attendees. \n\n**Note:** This API only returns a user's [unexpire[...]",
    "operationId": "webinars",
    "summary": "List webinars"
   },
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Webinars"
    ],
    "description": "Use this API to schedule a webinar for a user (webinar host). For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter. \n\nZoom users with a [Webinar plan](https://zoom.us/webinar) have access to creating and managing webinars. Webinars allow a host to broadcast a Zoom meeting to up to 10,000 attendees. \n\n**Scopes:** `webinar:write:admin`, `webinar:write`</br>**[Rate Limit Label]([...]",
    "operationId": "webinarCreate",
    "summary": "Create a webinar"
   }
  },
  "/users/summary": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Users"
    ],
    "description": "Use this API to get a summary of users, including the number and types of users in the account.\n\n **Scopes:** `user:read:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "userSummary",
    "summary": "Get user summary"
   }
  },
  "/webinars/{webinarId}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Webinars"
    ],
    "description": "Delete a Webinar.<br><br>\n**Scopes:** `webinar:write:admin` `webinar:write`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n**Prerequisites:**<br>\n* Pro or higher plan with a Webinar Add-on.",
    "operationId": "webinarDelete",
    "summary": "Delete a webinar"
   },
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Webinars"
    ],
    "description": "Zoom users with a [Webinar Plan](https://zoom.us/webinar) have access to creating and managing Webinars. Webinar allows a host to broadcast a Zoom meeting to up to 10,000 attendees.<br>Use this API to get details of a scheduled webinar.<br><br>\n**Scopes:** `webinar:read:admin` `webinar:read`<br> \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>**Prerequisites:**\n* Pro or higher plan with a Webinar Add-on.",
    "operationId": "webinar",
    "summary": "Get a webinar"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Webinars"
    ],
    "description": "Use this API to make updates to a scheduled webinar. \n\n**Scopes:** `webinar:write:admin`, `webinar:write` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` \n* This API has a daily rate limit of **100 requests per day**. The rate limit is applied to the `userId` of the **webinar host** used to make the request. \n\n**Prerequisites:** \n* A Pro or higher plan with a Webinar add-on.",
    "operationId": "webinarUpdate",
    "summary": "Update a webinar"
   }
  },
  "/webinars/{webinarId}/batch_registrants": {
   "post": {
    "security": [
     {
      "OAuth": []
     },
     {
      "Bearer": []
     }
    ],
    "tags": [
     "Webinars"
    ],
    "description": "Use this API to register up to 30 registrants at once for a scheduled webinar that requires [registration](https://support.zoom.us/hc/en-us/articles/204619915-Scheduling-a-webinar-with-registration). <br>\n\n**Prerequisites:**<br>\n* The webinar host must be a Licensed user.\n* The webinar should be of type `5`, i.e., it should be a scheduled webinar. Other types of webinars are not supported by this API.<br><br>\n**Scope:** `webinar:write`, `webinar:write:admin`<br>\n**[Rate[...]",
    "operationId": "addBatchWebinarRegistrants",
    "summary": "Perform batch registration"
   }
  },
  "/webinars/{webinarId}/invite_links": {
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Webinars"
    ],
    "description": "Use this API to create a batch of invitation links for a webinar.\n\n**Scopes**: `webinar:write:admin`, `webinar:write`</br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n**Prerequisites:**\n\n* Business, Education or API Plan with Webinar add-on.",
    "operationId": "webinarInviteLinksCreate",
    "summary": "Create webinar's invite links"
   }
  },
  "/webinars/{webinarId}/livestream": {
   "get": {
    "tags": [
     "Webinars"
    ],
    "description": "Zoom allows users to [live stream a webinar](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service) to a custom platform. Use this API to get a webinar's live stream configuration details such as Stream URL, Stream Key and Page URL.<br><br>\n**Prerequisites:**<br>\n* Pro or higher plan with a Webinar Add-on.<br>\n* Live streaming details must have been [configured](https://support.zoom.us/hc/en-us/articles/1150017778[...]",
    "operationId": "getWebinarLiveStreamDetails",
    "summary": "Get live stream details"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Webinars"
    ],
    "description": "Zoom allows users to [live stream a webinar](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service) to a custom platform. Use this API to update a webinar's live stream information.<br><br>\n**Prerequisites:**<br>\n* Pro or higher plan with a Webinar Add-on.<br>\n* Live streaming details must have been [configured](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Cust[...]",
    "operationId": "webinarLiveStreamUpdate",
    "summary": "Update a live stream"
   }
  },
  "/webinars/{webinarId}/livestream/status": {
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Webinars"
    ],
    "description": "Zoom allows users to [live stream a webinar](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service) to a custom platform. Use this API to update the status of a webinar's live stream.<br><br>\n**Prerequisites:**<br>\n* Pro or higher plan with a Webinar Add-on.<br>\n* Live streaming details must have been [configured](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Cu[...]",
    "operationId": "webinarLiveStreamStatusUpdate",
    "summary": "Update Live Stream Status"
   }
  },
  "/webinars/{webinarId}/panelists": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Webinars"
    ],
    "description": "Remove all the panelists from a Webinar.<br>\n**Scopes:** `webinar:write:admin` `webinar:write`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n**Prerequisites:**<br>\n* Pro or a higher plan with [Webinar Add-on](https://zoom.us/webinar).<br> ",
    "operationId": "webinarPanelistsDelete",
    "summary": "Remove panelists"
   },
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Webinars"
    ],
    "description": "Panelists in a Webinar can view and send video, screen share, annotate, etc and do much more compared to attendees in a Webinar. \n\nUse this API to list all the panelists of a Webinar.<br><br>\n**Scopes:** `webinar:read:admin` `webinar:read`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br>\n**Prerequisites:**<br>\n* Pro or a higher plan with [Webinar Add-on](https://zoom.us/webinar).<br> ",
    "operationId": "webinarPanelists",
    "summary": "List panelists"
   },
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Webinars"
    ],
    "description": "Panelists in a Webinar can view and send video, screen share, annotate, etc and do much more compared to attendees in a webinar.<br>Use this API to [add panelists](https://support.zoom.us/hc/en-us/articles/115005657826-Inviting-Panelists-to-a-Webinar#h_7550d59e-23f5-4703-9e22-e76bded1ed70) to a scheduled webinar.<br><br>\n**Scopes:** `webinar:write:admin` `webinar:write`<br> \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Me[...]",
    "operationId": "webinarPanelistCreate",
    "summary": "Add panelists"
   }
  },
  "/webinars/{webinarId}/panelists/{panelistId}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Webinars"
    ],
    "description": "[Remove](https://support.zoom.us/hc/en-us/articles/115005657826-Inviting-Panelists-to-a-Webinar#h_de31f237-a91c-4fb2-912b-ecfba8ec5ffb) a single panelist from a webinar.<br> You can retrieve the `panelistId` by calling **List Panelists API**.<br><br>\n**Scopes:** `webinar:write:admin` `webinar:write`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n\n\n**Prerequisites:**<br>\n* Pro or a higher plan with [Web[...]",
    "operationId": "webinarPanelistDelete",
    "summary": "Remove a panelist"
   }
  },
  "/webinars/{webinarId}/polls": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Webinars"
    ],
    "description": "List all the [polls](https://support.zoom.us/hc/en-us/articles/203749865-Polling-for-Webinars) of a Webinar.<br><br>\n**Scopes:** `webinar:read:admin` `webinar:read`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n\n",
    "operationId": "webinarPolls",
    "summary": "List a webinar's polls "
   },
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Webinars"
    ],
    "description": "Create a [poll](https://support.zoom.us/hc/en-us/articles/203749865-Polling-for-Webinars) for a webinar.<br><br>\n**Scopes:** `webinar:write:admin` `webinar:write`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n\n",
    "operationId": "webinarPollCreate",
    "summary": "Create a webinar's poll"
   }
  },
  "/webinars/{webinarId}/polls/{pollId}": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Webinars"
    ],
    "description": "Delete a webinar's [poll](https://support.zoom.us/hc/en-us/articles/203749865-Polling-for-Webinars).<br><br>\n**Scopes:** `webinar:write:admin` `webinar:write`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n\n",
    "operationId": "webinarPollDelete",
    "summary": "Delete a webinar poll"
   },
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Webinars"
    ],
    "description": "Get a webinar's [poll](https://support.zoom.us/hc/en-us/articles/203749865-Polling-for-Webinars) details.<br><br>\n**Scopes:** `webinar:read:admin` `webinar:read`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n\n",
    "operationId": "webinarPollGet",
    "summary": "Get a webinar poll"
   },
   "put": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Webinars"
    ],
    "description": "Update a webinar's [poll](https://support.zoom.us/hc/en-us/articles/203749865-Polling-for-Webinars).<br><br>\n**Scopes:** `webinar:write:admin` `webinar:write`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n\n",
    "operationId": "webinarPollUpdate",
    "summary": "Update a webinar poll"
   }
  },
  "/webinars/{webinarId}/registrants": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Webinars"
    ],
    "description": "Zoom users with a [Webinar Plan](https://zoom.us/webinar) have access to creating and managing Webinars. Webinar allows a host to broadcast a Zoom meeting to up to 10,000 attendees. Scheduling a [Webinar with registration](https://support.zoom.us/hc/en-us/articles/204619915-Scheduling-a-Webinar-with-Registration) requires your registrants to complete a brief form before receiving the link to join the Webinar.<br>\nUse this API to list all the users that have registered for a [...]",
    "operationId": "webinarRegistrants",
    "summary": "List webinar registrants"
   },
   "post": {
    "summary": "Add a webinar registrant",
    "description": "Use this API to create and submit a user's registration for a webinar. Zoom users with a [Webinar plan](https://zoom.us/webinar) have access to creating and managing webinars. Webinars allow hosts to broadcast a Zoom meeting to up to 10,000 attendees. Scheduling a [webinar with registration](https://support.zoom.us/hc/en-us/articles/204619915-Scheduling-a-Webinar-with-Registration) requires your registrants to complete a brief form before receiving the link to join the webina[...]",
    "operationId": "webinarRegistrantCreate",
    "tags": [
     "Webinars"
    ],
    "security": [
     {
      "OAuth": []
     }
    ]
   }
  },
  "/webinars/{webinarId}/registrants/questions": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Webinars"
    ],
    "description": "Scheduling a [Webinar with registration](https://support.zoom.us/hc/en-us/articles/204619915-Scheduling-a-Webinar-with-Registration) requires your registrants to complete a brief form with fields and questions before they can receive the link to join the Webinar.<br>Use this API to list registration questions and fields that are to be answered by users while registering for a Webinar.<br>\n**Prerequisites:**<br>  \n* Pro or higher plan with a Webinar Add-on.\n**Scopes:** `web[...]",
    "operationId": "webinarRegistrantsQuestionsGet",
    "summary": "List registration questions"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Webinars"
    ],
    "description": "Scheduling a [Webinar with registration](https://support.zoom.us/hc/en-us/articles/204619915-Scheduling-a-Webinar-with-Registration) requires your registrants to complete a brief form with fields and questions before they can receive the link to join the Webinar.<br>Use this API to update registration questions and fields of a scheduled Webinar that are to be answered by users while registering for a Webinar.<br><br>\n**Prerequisites:**<br>  \n* Pro or higher plan with a Webi[...]",
    "operationId": "webinarRegistrantQuestionUpdate",
    "summary": "Update registration questions"
   }
  },
  "/webinars/{webinarId}/registrants/status": {
   "put": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Webinars"
    ],
    "description": "Use this API to update webinar registrants' registration status. You can approve or deny a registrant, or revoke a registrant's approval. \n\n**Scopes:** `webinar:write:admin`, `webinar:write` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "webinarRegistrantStatus",
    "summary": "Update registrant's status"
   }
  },
  "/webinars/{webinarId}/registrants/{registrantId}": {
   "delete": {
    "tags": [
     "Webinars"
    ],
    "description": "Delete a webinar registrant.<br><br>\n**Scopes**: `webinar:write:admin` `webinar:write`<br>\n <br>\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "deleteWebinarRegistrant",
    "summary": "Delete a webinar registrant"
   },
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Webinars"
    ],
    "description": "Zoom users with a [Webinar Plan](https://zoom.us/webinar) have access to creating and managing Webinars. Webinar allows a host to broadcast a Zoom meeting to up to 10,000 attendees. Scheduling a [Webinar with registration](https://support.zoom.us/hc/en-us/articles/204619915-Scheduling-a-Webinar-with-Registration) requires your registrants to complete a brief form before receiving the link to join the Webinar.<br>Use this API to get details on a specific user who has registere[...]",
    "operationId": "webinarRegistrantGet",
    "summary": "Get a webinar registrant"
   }
  },
  "/webinars/{webinarId}/status": {
   "put": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Webinars"
    ],
    "description": "Update a webinar's status. Use this API to end an ongoing webinar.<br><br>\n**Scopes:** `webinar:write:admin` `webinar:write`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n**Prerequisites:**<br>\n* The account must hold a valid [Webinar plan](https://zoom.us/webinar).",
    "operationId": "webinarStatus",
    "summary": "Update webinar status"
   }
  },
  "/webinars/{webinarId}/survey": {
   "delete": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Webinars"
    ],
    "description": "Use this API to delete a [webinar survey](https://support.zoom.us/hc/en-us/articles/360048745651). \n\n **Scopes:** `webinar:write`, `webinar:write:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` \n\n **Prerequisites:** \n* A Pro or higher plan with the Webinar Add-on. \n* The [**Webinar Survey**](https://support.zoom.us/hc/en-us/articles/360061293191-Enabling-webinar-survey) feature enabled in the host's acc[...]",
    "operationId": "webinarSurveyDelete",
    "summary": "Delete a webinar survey"
   },
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Webinars"
    ],
    "description": "Use this API to return information about a [webinar survey](https://support.zoom.us/hc/en-us/articles/360048745651). \n\n **Scopes:** `webinar:read`, `webinar:read:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` \n\n **Prerequisites:** \n* A Pro or higher plan with the Webinar add-on. \n* The [**Webinar Survey**](https://support.zoom.us/hc/en-us/articles/360061293191-Enabling-webinar-survey) feature enabled i[...]",
    "operationId": "webinarSurveyGet",
    "summary": "Get a webinar survey"
   },
   "patch": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Webinars"
    ],
    "description": "Use this API to update a [webinar survey](https://support.zoom.us/hc/en-us/articles/360048745651). \n\n **Scopes:** `webinar:write`, `webinar:write:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` \n\n **Prerequisites:** \n* A Pro or higher plan with the Webinar add-on. \n* The [**Webinar Survey**](https://support.zoom.us/hc/en-us/articles/360061293191-Enabling-webinar-survey) feature enabled in the host's acc[...]",
    "operationId": "webinarSurveyUpdate",
    "summary": "Update a webinar survey"
   }
  },
  "/webinars/{webinarId}/tracking_sources": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Webinars"
    ],
    "description": "[Webinar Registration Tracking Sources](https://support.zoom.us/hc/en-us/articles/360000315683-Webinar-Registration-Source-Tracking) allow you to see where your registrants are coming from if you share the webinar registration page in multiple platforms. You can then use the source tracking to see the number of registrants generated from each platform.<br> Use this API to list information on all the tracking sources of a Webinar.<br>\n**Scopes:** `webinar:read:admin`, `webina[...]",
    "operationId": "getTrackingSources",
    "summary": "Get webinar tracking sources"
   }
  },
  "/webinars/{webinarId}/token": {
   "get": {
    "summary": "Get webinar's token",
    "description": "Use this API to get a webinar's [closed caption token (caption URL)](https://support.zoom.us/hc/en-us/articles/115002212983-Using-a-third-party-closed-captioning-service). This token lets you use a third-party service to stream text to their closed captioning software to the Zoom webinar. \n\n**Scopes:** `webinar:read`, `webinar:read:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` \n\n**Prerequisites:** \n* A[...]",
    "tags": [
     "Webinars"
    ],
    "operationId": "webinarToken",
    "security": [
     {
      "OAuth": []
     }
    ]
   }
  },
  "/webinars/{webinarId}/branding": {
   "get": {
    "summary": "Get webinar's session branding",
    "description": "Use this API to get the webinar's [Session Branding](https://support.zoom.us/hc/en-us/articles/4836268732045-Using-Webinar-Session-Branding) information. Session branding lets hosts visually customize a webinar by setting a webinar wallpaper that displays behind video tiles. Session branding also lets hosts set the Virtual Background for and apply name tags to hosts, alternative hosts, panelists, interpreters, and speakers. \n\n **Scopes:** `webinar:read`, `webinar:read:admin[...]",
    "tags": [
     "Webinars"
    ],
    "operationId": "getWebinarBranding",
    "security": [
     {
      "OAuth": []
     }
    ]
   }
  },
  "/webinars/{webinarId}/branding/virtual_backgrounds": {
   "post": {
    "summary": "Upload a webinar's branding Virtual Background",
    "description": "Use this API to upload a webinar's session branding [Virtual Background](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background). Hosts and panelists can select and use these Virtual Backgrounds during the webinar. Branding Virtual Background files have the following restrictions: \n* A webinar cannot exceed more than 10 Virtual Background files. \n* You can only upload image files that are in JPG/JPEG, GIF or PNG format. \n* The Virtual Background file size c[...]",
    "operationId": "uploadWebinarBrandingVB",
    "tags": [
     "Webinars"
    ]
   },
   "patch": {
    "summary": "Set webinar's default branding Virtual Background",
    "description": "Use this API to set a webinar's default session branding [Virtual Background](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background). \n\n **Scopes:** `webinar:write`, `webinar:write:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` \n\n **Prerequisites:** \n* The **Webinar Session Branding** setting enabled.",
    "operationId": "setWebinarBrandingVB",
    "tags": [
     "Webinars"
    ]
   },
   "delete": {
    "summary": "Delete a webinar's branding Virtual Backgrounds",
    "description": "Use this API to delete a webinar's session branding [Virtual Background](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background). \n\n **Scopes:** `webinar:write`, `webinar:write:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` \n\n **Prerequisites:** \n* The **Webinar Session Branding** setting enabled.",
    "operationId": "deleteWebinarBrandingVB",
    "tags": [
     "Webinars"
    ]
   }
  },
  "/webinars/{webinarId}/branding/wallpaper": {
   "post": {
    "summary": "Upload a webinar's branding wallpaper",
    "description": "Use this API to upload a webinar's session branding wallpaper file. Webinar branding wallpaper files have the following requirements: \n* A webinar can only have one wallpaper file. \n* You can only upload image files that are in JPG/JPEG, GIF, or PNG format. \n* Image files must be 16:9 ratio. The recommended image size is 1920 x 1080 pixels (px). \n* The wallpaper file size cannot exceed 15 megabytes (MB). \n\n **Scopes:** `webinar:write`, `webinar:write:admin` <br> **[Rate[...]",
    "operationId": "uploadWebinarBrandingWallpaper",
    "tags": [
     "Webinars"
    ]
   },
   "delete": {
    "summary": "Delete a webinar's branding wallpaper",
    "description": "Use this API to delete a webinar's session branding wallpaper file. \n\n **Scopes:** `webinar:write`, `webinar:write:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` \n\n **Prerequisites:** \n* The **Webinar Session Branding** setting enabled.",
    "operationId": "deleteWebinarBrandingWallpaper",
    "tags": [
     "Webinars"
    ]
   }
  },
  "/webinars/{webinarId}/branding/name_tags": {
   "post": {
    "summary": "Create a webinar's branding name tag",
    "description": "Use this API to create a webinar's [Session Branding](https://support.zoom.us/hc/en-us/articles/4836268732045-Using-Webinar-Session-Branding) name tag. There's a limit of 20 name tags per webinar. **Scopes:** `webinar:write`, `webinar:write:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` \n\n**Prerequisites:** \n*  The **Webinar Session Branding** setting enabled.",
    "operationId": "createWebinarBrandingNameTag",
    "tags": [
     "Webinars"
    ]
   },
   "delete": {
    "summary": "Delete a webinar's branding name tag",
    "description": "Use this API to delete a webinar's [Session Branding](https://support.zoom.us/hc/en-us/articles/4836268732045-Using-Webinar-Session-Branding) name tag. \n\n **Scopes:** `webinar:write`, `webinar:write:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` \n\n **Prerequisites:** \n* The **Webinar Session Branding** setting enabled.",
    "operationId": "deleteWebinarBrandingNameTag",
    "tags": [
     "Webinars"
    ]
   }
  },
  "/webinars/{webinarId}/branding/name_tags/{nameTagId}": {
   "patch": {
    "summary": "Update a webinar's branding name tag",
    "description": "Use this API to update a webinar's [Session Branding](https://support.zoom.us/hc/en-us/articles/4836268732045-Using-Webinar-Session-Branding) name tag. **Scopes:** `webinar:write`, `webinar:write:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` \n\n**Prerequisites:** \n*  The **Webinar Session Branding** setting enabled.",
    "operationId": "updateWebinarBrandingNameTag",
    "tags": [
     "Webinars"
    ]
   }
  },
  "/webinars/{webinarId}/jointoken/local_recording": {
   "get": {
    "summary": "Get a webinar's join token for local recording",
    "description": "Use this API to get a webinar's join token to allow for local recording. The join token lets a recording bot implemented using Zoom Meeting SDK to connect to a Zoom webinar. The recording bot can then automatically start locally recording. This supports both regular and raw local recording types. \n\n **Scopes:** `webinar_token:read:admin:local_recording`, `webinar_token:read:local_recording` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits[...]",
    "tags": [
     "Webinars"
    ],
    "operationId": "webinarLocalRecordingJoinToken",
    "security": [
     {
      "OAuth": []
     }
    ]
   }
  },
  "/webinars/{webinarId}/jointoken/local_archiving": {
   "get": {
    "summary": "Get a webinar's archive token for local archiving",
    "description": "Use this API to get a webinar's archive token to allow local archiving. The archive token allows a meeting SDK app or bot to get archive permission to access the webinar's raw audio and video media stream in real-time. \n\n **Scopes:** `webinar_token:read:admin:local_archiving` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` \n\n **Prerequisites:** \n* A Pro or higher plan with a Webinar Add-on. \n* The **Archive me[...]",
    "tags": [
     "Webinars"
    ],
    "operationId": "webinarLocalArchivingArchiveToken",
    "security": [
     {
      "OAuth": []
     }
    ]
   }
  },
  "/webinars/{webinarId}/jointoken/live_streaming": {
   "get": {
    "summary": "Get a webinar's join token for live streaming",
    "description": "Use this API to get a webinar's archive token to allow live streaming. The join token allows a recording bot implemented using Zoom meeting SDK to connect to a Zoom meeting \"hosted by the issuer of the token\", and can call the streaming method automatically. It supports both regular live streaming, and raw streaming. \n\n **Scopes:** `webinar_token:read:admin:live_streaming`, `webinar_token:read:live_streaming` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-[...]",
    "tags": [
     "Webinars"
    ],
    "operationId": "webinarLiveStreamingJoinToken",
    "security": [
     {
      "OAuth": []
     }
    ]
   }
  },
  "/live_webinars/{webinarId}/chat/messages/{messageId}": {
   "delete": {
    "summary": "Delete a live webinar message",
    "description": "Deletes a message in a live webinar based on ID. \n\n**Scopes:** `webinar:write` `webinar:write:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "deleteWebinarChatMessageById",
    "tags": [
     "Webinars"
    ],
    "security": [
     {
      "OAuth": []
     }
    ]
   }
  },
  "/workspaces": {
   "get": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Workspaces"
    ],
    "description": "Use this API to list a location's workspaces. \n\n **Scopes:** `workspace:read`, `workspace:read:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "listWorkspaces",
    "summary": "List workspaces"
   },
   "post": {
    "security": [
     {
      "OAuth": []
     }
    ],
    "tags": [
     "Workspaces"
    ],
    "description": "Use this API to create workspaces. \n\n **Scopes:** `workspace:write:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
[...]
